/** EPA Emission Factors Hub 2026 published types. Generated — do not edit by hand. */

export const EPA_GWP_CH4_AR6 = 27
export const EPA_GWP_N2O_AR6 = 273

export type EpaEgridRow = { acronym: string; name: string; lbCo2: number; lbCh4: number; lbN2o: number; ggl: number }
export type EpaFuelRow = { key: string; name: string; kg: number; unit: string; group: string; table: '1' | '2' }
export type EpaGwpRow = { key: string; name: string; gwp: number; kind: 'pure' | 'blend' }
export type EpaActivityRow = { key: string; name: string; kg: number; unit: string }
export type EpaWasteRow = { key: string; material: string; route: string; kgPerShortTon: number }

export const EPA_EGRID_SUBREGIONS: EpaEgridRow[] = [
  { acronym: 'AKGD', name: 'ASCC Alaska Grid', lbCo2: 914.7, lbCh4: 0.092, lbN2o: 0.013, ggl: 0.044 },
  { acronym: 'AKMS', name: 'ASCC Miscellaneous', lbCo2: 493.8, lbCh4: 0.024, lbN2o: 0.004, ggl: 0.044 },
  { acronym: 'AZNM', name: 'WECC Southwest', lbCo2: 665.8, lbCh4: 0.035, lbN2o: 0.005, ggl: 0.044 },
  { acronym: 'CAMX', name: 'WECC California', lbCo2: 403.6, lbCh4: 0.025, lbN2o: 0.003, ggl: 0.044 },
  { acronym: 'ERCT', name: 'ERCOT All', lbCo2: 700.7, lbCh4: 0.04, lbN2o: 0.006, ggl: 0.044 },
  { acronym: 'FRCC', name: 'FRCC All', lbCo2: 763.7, lbCh4: 0.035, lbN2o: 0.004, ggl: 0.044 },
  { acronym: 'HIMS', name: 'HICC Miscellaneous', lbCo2: 1087.7, lbCh4: 0.072, lbN2o: 0.012, ggl: 0.048 },
  { acronym: 'HIOA', name: 'HICC Oahu', lbCo2: 1478, lbCh4: 0.136, lbN2o: 0.022, ggl: 0.048 },
  { acronym: 'MROE', name: 'MRO East', lbCo2: 1297.3, lbCh4: 0.096, lbN2o: 0.014, ggl: 0.044 },
  { acronym: 'MROW', name: 'MRO West', lbCo2: 862.6, lbCh4: 0.089, lbN2o: 0.013, ggl: 0.044 },
  { acronym: 'NEWE', name: 'NPCC New England', lbCo2: 540.3, lbCh4: 0.059, lbN2o: 0.008, ggl: 0.044 },
  { acronym: 'NWPP', name: 'WECC Northwest', lbCo2: 579.2, lbCh4: 0.047, lbN2o: 0.007, ggl: 0.044 },
  { acronym: 'NYCW', name: 'NPCC NYC/Westchester', lbCo2: 883.2, lbCh4: 0.022, lbN2o: 0.002, ggl: 0.044 },
  { acronym: 'NYLI', name: 'NPCC Long Island', lbCo2: 1170.6, lbCh4: 0.139, lbN2o: 0.018, ggl: 0.044 },
  { acronym: 'NYUP', name: 'NPCC Upstate NY', lbCo2: 272, lbCh4: 0.011, lbN2o: 0.001, ggl: 0.044 },
  { acronym: 'PRMS', name: 'Puerto Rico Miscellaneous', lbCo2: 1594.5, lbCh4: 0.085, lbN2o: 0.014, ggl: 0.14 },
  { acronym: 'RFCE', name: 'RFC East', lbCo2: 618.6, lbCh4: 0.038, lbN2o: 0.005, ggl: 0.044 },
  { acronym: 'RFCM', name: 'RFC Michigan', lbCo2: 982.5, lbCh4: 0.086, lbN2o: 0.012, ggl: 0.044 },
  { acronym: 'RFCW', name: 'RFC West', lbCo2: 889.6, lbCh4: 0.068, lbN2o: 0.01, ggl: 0.044 },
  { acronym: 'RMPA', name: 'WECC Rockies', lbCo2: 959, lbCh4: 0.079, lbN2o: 0.011, ggl: 0.044 },
  { acronym: 'SPNO', name: 'SPP North', lbCo2: 779, lbCh4: 0.076, lbN2o: 0.011, ggl: 0.044 },
  { acronym: 'SPSO', name: 'SPP South', lbCo2: 850.6, lbCh4: 0.051, lbN2o: 0.007, ggl: 0.044 },
  { acronym: 'SRMV', name: 'SERC Mississippi Valley', lbCo2: 730.8, lbCh4: 0.029, lbN2o: 0.004, ggl: 0.044 },
  { acronym: 'SRMW', name: 'SERC Midwest', lbCo2: 1150.4, lbCh4: 0.123, lbN2o: 0.018, ggl: 0.044 },
  { acronym: 'SRSO', name: 'SERC South', lbCo2: 796.5, lbCh4: 0.056, lbN2o: 0.008, ggl: 0.044 },
  { acronym: 'SRTV', name: 'SERC Tennessee Valley', lbCo2: 940.4, lbCh4: 0.08, lbN2o: 0.011, ggl: 0.044 },
  { acronym: 'SRVC', name: 'SERC Virginia/Carolina', lbCo2: 637.4, lbCh4: 0.047, lbN2o: 0.007, ggl: 0.044 },
  { acronym: 'US', name: 'US Average', lbCo2: 747.9, lbCh4: 0.054, lbN2o: 0.007, ggl: 0.044 },
]

export const EPA_STATIONARY_FUELS: EpaFuelRow[] = [
  { key: 'epa_stat_anthracite_short_ton', name: 'Anthracite', kg: 2620.372, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_bituminous_short_ton', name: 'Bituminous', kg: 2343.318, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_sub_bituminous_short_ton', name: 'Sub-bituminous', kg: 1688.774, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_lignite_short_ton', name: 'Lignite', kg: 1399.491, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_mixed_commercial_sector_short_ton', name: 'Mixed (Commercial Sector)', kg: 2031.627, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_mixed_electric_power_sector_short_ton', name: 'Mixed (Electric Power Sector)', kg: 1899.595, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_mixed_industrial_coking_short_ton', name: 'Mixed (Industrial Coking)', kg: 2487.269, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_mixed_industrial_sector_short_ton', name: 'Mixed (Industrial Sector)', kg: 2132.47, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_coal_coke_short_ton', name: 'Coal Coke', kg: 2837.291, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_municipal_solid_waste_short_ton', name: 'Municipal Solid Waste', kg: 922.052, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_petroleum_coke_solid_short_ton', name: 'Petroleum Coke (Solid)', kg: 3132.318, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_plastics_short_ton', name: 'Plastics', kg: 2926.512, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_tires_short_ton', name: 'Tires', kg: 2463.406, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_agricultural_byproducts_short_ton', name: 'Agricultural Byproducts', kg: 991.683, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_peat_short_ton', name: 'Peat', kg: 911.194, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_solid_byproducts_short_ton', name: 'Solid Byproducts', kg: 1116.976, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_wood_and_wood_residuals_short_ton', name: 'Wood and Wood Residuals', kg: 1660.601, unit: 'short ton', group: 'Solid', table: '1' },
  { key: 'epa_stat_natural_gas_scf', name: 'Natural Gas', kg: 0.05449511, unit: 'scf', group: 'Gaseous', table: '1' },
  { key: 'epa_stat_blast_furnace_gas_scf', name: 'Blast Furnace Gas', kg: 0.025242511, unit: 'scf', group: 'Gaseous', table: '1' },
  { key: 'epa_stat_coke_oven_gas_scf', name: 'Coke Oven Gas', kg: 0.028084156, unit: 'scf', group: 'Gaseous', table: '1' },
  { key: 'epa_stat_fuel_gas_scf', name: 'Fuel Gas', kg: 0.082229837, unit: 'scf', group: 'Gaseous', table: '1' },
  { key: 'epa_stat_propane_gas_scf', name: 'Propane Gas', kg: 0.155246026, unit: 'scf', group: 'Gaseous', table: '1' },
  { key: 'epa_stat_landfill_gas_scf', name: 'Landfill Gas', kg: 0.025379442, unit: 'scf', group: 'Gaseous', table: '1' },
  { key: 'epa_stat_other_biomass_gases_scf', name: 'Other Biomass Gases', kg: 0.034275341, unit: 'scf', group: 'Gaseous', table: '1' },
  { key: 'epa_stat_asphalt_and_road_oil_gal_us', name: 'Asphalt and Road Oil', kg: 11.94726, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_aviation_gasoline_gal_us', name: 'Aviation Gasoline', kg: 8.33883, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_butane_gal_us', name: 'Butane', kg: 6.69475, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_butylene_gal_us', name: 'Butylene', kg: 7.24502, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_crude_oil_gal_us', name: 'Crude Oil', kg: 10.32291, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_distillate_fuel_oil_no_1_gal_us', name: 'Distillate Fuel Oil No. 1', kg: 10.21318, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_distillate_fuel_oil_no_2_gal_us', name: 'Distillate Fuel Oil No. 2', kg: 10.24291, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_distillate_fuel_oil_no_4_gal_us', name: 'Distillate Fuel Oil No. 4', kg: 10.99645, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_ethane_gal_us', name: 'Ethane', kg: 4.06632, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_ethylene_gal_us', name: 'Ethylene', kg: 3.84278, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_heavy_gas_oils_gal_us', name: 'Heavy Gas Oils', kg: 11.12645, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_isobutane_gal_us', name: 'Isobutane', kg: 6.45448, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_isobutylene_gal_us', name: 'Isobutylene', kg: 7.11475, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_kerosene_gal_us', name: 'Kerosene', kg: 10.18291, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_kerosene_type_jet_fuel_gal_us', name: 'Kerosene-Type Jet Fuel', kg: 9.78291, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_liquefied_petroleum_gases_lpg_gal_us', name: 'Liquefied Petroleum Gases (LPG)', kg: 5.70394, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_lubricants_gal_us', name: 'Lubricants', kg: 10.72618, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_motor_gasoline_gal_us', name: 'Motor Gasoline', kg: 8.8121, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_naphtha_lt401_deg_f_gal_us', name: 'Naphtha (<401 deg F)', kg: 8.5321, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_natural_gasoline_gal_us', name: 'Natural Gasoline', kg: 7.38802, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_other_oil_gt401_deg_f_gal_us', name: 'Other Oil (>401 deg F)', kg: 10.62318, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_pentanes_plus_gal_us', name: 'Pentanes Plus', kg: 7.72802, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_petrochemical_feedstocks_gal_us', name: 'Petrochemical Feedstocks', kg: 8.9121, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_propane_gal_us', name: 'Propane', kg: 5.74094, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_propylene_gal_us', name: 'Propylene', kg: 6.19094, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_residual_fuel_oil_no_5_gal_us', name: 'Residual Fuel Oil No. 5', kg: 10.24318, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_residual_fuel_oil_no_6_gal_us', name: 'Residual Fuel Oil No. 6', kg: 11.30672, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_special_naphtha_gal_us', name: 'Special Naphtha', kg: 9.0721, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_unfinished_oils_gal_us', name: 'Unfinished Oils', kg: 10.39318, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_used_oil_gal_us', name: 'Used Oil', kg: 10.24291, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_biodiesel_100pct_gal_us', name: 'Biodiesel (100%)', kg: 9.45651, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_ethanol_100pct_gal_us', name: 'Ethanol (100%)', kg: 5.75516, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_rendered_animal_fat_gal_us', name: 'Rendered Animal Fat', kg: 8.88651, unit: 'gal (US)', group: 'Liquid', table: '1' },
  { key: 'epa_stat_vegetable_oil_gal_us', name: 'Vegetable Oil', kg: 9.79624, unit: 'gal (US)', group: 'Liquid', table: '1' },
]

export const EPA_MOBILE_CO2_FUELS: EpaFuelRow[] = [
  { key: 'epa_mobile_aviation_gasoline_gal_us', name: 'Aviation Gasoline', kg: 8.31, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'epa_mobile_biodiesel_100pct_gal_us', name: 'Biodiesel (100%)', kg: 9.45, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'epa_mobile_compressed_natural_gas_cng_scf', name: 'Compressed Natural Gas (CNG)', kg: 0.05444, unit: 'scf', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'diesel_us_gallon', name: 'Diesel Fuel', kg: 10.21, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'epa_mobile_ethanol_100pct_gal_us', name: 'Ethanol (100%)', kg: 5.75, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'epa_mobile_kerosene_type_jet_fuel_gal_us', name: 'Kerosene-Type Jet Fuel', kg: 9.75, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'epa_mobile_liquefied_natural_gas_lng_gal_us', name: 'Liquefied Natural Gas (LNG)', kg: 4.5, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'epa_mobile_liquefied_petroleum_gases_lpg_gal_us', name: 'Liquefied Petroleum Gases (LPG)', kg: 5.68, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'petrol_us_gallon', name: 'Motor Gasoline', kg: 8.78, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
  { key: 'epa_mobile_residual_fuel_oil_gal_us', name: 'Residual Fuel Oil', kg: 11.27, unit: 'gal (US)', group: 'Mobile CO2 (Table 2)', table: '2' },
]

export const EPA_GWP_GASES: EpaGwpRow[] = [
  { key: 'epa_gwp_carbon_dioxide_kg', name: 'Carbon dioxide', gwp: 1, kind: 'pure' },
  { key: 'epa_gwp_methane_non_fossil_kg', name: 'Methane (non-fossil)', gwp: 27, kind: 'pure' },
  { key: 'mine_ch4_epa_fossil_kg', name: 'Fossil methane', gwp: 29.8, kind: 'pure' },
  { key: 'epa_gwp_nitrous_oxide_kg', name: 'Nitrous oxide', gwp: 273, kind: 'pure' },
  { key: 'epa_gwp_hfc_23_kg', name: 'HFC-23', gwp: 14600, kind: 'pure' },
  { key: 'epa_gwp_hfc_32_kg', name: 'HFC-32', gwp: 771, kind: 'pure' },
  { key: 'epa_gwp_hfc_41_kg', name: 'HFC-41', gwp: 135, kind: 'pure' },
  { key: 'epa_gwp_hfc_125_kg', name: 'HFC-125', gwp: 3740, kind: 'pure' },
  { key: 'epa_gwp_hfc_134_kg', name: 'HFC-134', gwp: 1260, kind: 'pure' },
  { key: 'r134a_epa_kg', name: 'HFC-134a', gwp: 1530, kind: 'pure' },
  { key: 'epa_gwp_hfc_143_kg', name: 'HFC-143', gwp: 364, kind: 'pure' },
  { key: 'epa_gwp_hfc_143a_kg', name: 'HFC-143a', gwp: 5810, kind: 'pure' },
  { key: 'epa_gwp_hfc_152_kg', name: 'HFC-152', gwp: 21.5, kind: 'pure' },
  { key: 'epa_gwp_hfc_152a_kg', name: 'HFC-152a', gwp: 164, kind: 'pure' },
  { key: 'epa_gwp_hfc_161_kg', name: 'HFC-161', gwp: 4.84, kind: 'pure' },
  { key: 'epa_gwp_hfc_227ca_kg', name: 'HFC-227ca', gwp: 2980, kind: 'pure' },
  { key: 'epa_gwp_hfc_227ea_kg', name: 'HFC-227ea', gwp: 3600, kind: 'pure' },
  { key: 'epa_gwp_hfc_236cb_kg', name: 'HFC-236cb', gwp: 1350, kind: 'pure' },
  { key: 'epa_gwp_hfc_236ea_kg', name: 'HFC-236ea', gwp: 1500, kind: 'pure' },
  { key: 'epa_gwp_hfc_236fa_kg', name: 'HFC-236fa', gwp: 8690, kind: 'pure' },
  { key: 'epa_gwp_hfc_245ca_kg', name: 'HFC-245ca', gwp: 787, kind: 'pure' },
  { key: 'epa_gwp_hfc_245cb_kg', name: 'HFC-245cb', gwp: 4550, kind: 'pure' },
  { key: 'epa_gwp_hfc_245ea_kg', name: 'HFC-245ea', gwp: 255, kind: 'pure' },
  { key: 'epa_gwp_hfc_245eb_kg', name: 'HFC-245eb', gwp: 325, kind: 'pure' },
  { key: 'epa_gwp_hfc_245fa_kg', name: 'HFC-245fa', gwp: 962, kind: 'pure' },
  { key: 'epa_gwp_hfc_263fb_kg', name: 'HFC-263fb', gwp: 74.8, kind: 'pure' },
  { key: 'epa_gwp_hfc_272ca_kg', name: 'HFC-272ca', gwp: 599, kind: 'pure' },
  { key: 'epa_gwp_hfc_329p_kg', name: 'HFC-329p', gwp: 2890, kind: 'pure' },
  { key: 'epa_gwp_hfc_365mfc_kg', name: 'HFC-365mfc', gwp: 914, kind: 'pure' },
  { key: 'epa_gwp_hfc_43_10mee_kg', name: 'HFC-43-10mee', gwp: 1600, kind: 'pure' },
  { key: 'epa_gwp_sulfur_hexafluoride_kg', name: 'Sulfur hexafluoride', gwp: 24300, kind: 'pure' },
  { key: 'epa_gwp_nitrogen_trifluoride_kg', name: 'Nitrogen trifluoride', gwp: 17400, kind: 'pure' },
  { key: 'epa_gwp_pfc_14_kg', name: 'PFC-14', gwp: 7380, kind: 'pure' },
  { key: 'epa_gwp_pfc_116_kg', name: 'PFC-116', gwp: 12400, kind: 'pure' },
  { key: 'epa_gwp_pfc_218_kg', name: 'PFC-218', gwp: 9290, kind: 'pure' },
  { key: 'epa_gwp_pfc_318_kg', name: 'PFC-318', gwp: 10200, kind: 'pure' },
  { key: 'epa_gwp_pfc_31_10_kg', name: 'PFC-31-10', gwp: 10000, kind: 'pure' },
  { key: 'epa_gwp_pfc_41_12_kg', name: 'PFC-41-12', gwp: 9220, kind: 'pure' },
  { key: 'epa_gwp_pfc_51_14_kg', name: 'PFC-51-14', gwp: 8620, kind: 'pure' },
  { key: 'epa_gwp_pfc_61_16_kg', name: 'PFC-61-16', gwp: 8410, kind: 'pure' },
  { key: 'epa_gwp_pfc_71_18_kg', name: 'PFC-71-18', gwp: 8260, kind: 'pure' },
  { key: 'epa_gwp_pfc_91_18_kg', name: 'PFC-91-18', gwp: 7480, kind: 'pure' },
  { key: 'epa_gwp_pfc_1114_kg', name: 'PFC-1114', gwp: 0.004, kind: 'pure' },
  { key: 'epa_gwp_pfc_1216_kg', name: 'PFC-1216', gwp: 0.09, kind: 'pure' },
  { key: 'epa_gwp_r_401a_kg', name: 'R-401A', gwp: 21, kind: 'blend' },
  { key: 'epa_gwp_r_401b_kg', name: 'R-401B', gwp: 18, kind: 'blend' },
  { key: 'epa_gwp_r_401c_kg', name: 'R-401C', gwp: 25, kind: 'blend' },
  { key: 'epa_gwp_r_402a_kg', name: 'R-402A', gwp: 2244, kind: 'blend' },
  { key: 'epa_gwp_r_402b_kg', name: 'R-402B', gwp: 1421, kind: 'blend' },
  { key: 'epa_gwp_r_403b_kg', name: 'R-403B', gwp: 3623, kind: 'blend' },
  { key: 'r404a_epa_kg', name: 'R-404A', gwp: 4728, kind: 'blend' },
  { key: 'epa_gwp_r_406a_kg', name: 'R-406A', gwp: 0, kind: 'blend' },
  { key: 'epa_gwp_r_407a_kg', name: 'R-407A', gwp: 2262, kind: 'blend' },
  { key: 'epa_gwp_r_407b_kg', name: 'R-407B', gwp: 3001, kind: 'blend' },
  { key: 'epa_gwp_r_407c_kg', name: 'R-407C', gwp: 1908, kind: 'blend' },
  { key: 'epa_gwp_r_407d_kg', name: 'R-407D', gwp: 1748, kind: 'blend' },
  { key: 'epa_gwp_r_408a_kg', name: 'R-408A', gwp: 2934, kind: 'blend' },
  { key: 'epa_gwp_r_409a_kg', name: 'R-409A', gwp: 0, kind: 'blend' },
  { key: 'r410a_epa_kg', name: 'R-410A', gwp: 2256, kind: 'blend' },
  { key: 'epa_gwp_r_410b_kg', name: 'R-410B', gwp: 2404, kind: 'blend' },
  { key: 'epa_gwp_r_411a_kg', name: 'R-411A', gwp: 18, kind: 'blend' },
  { key: 'epa_gwp_r_411b_kg', name: 'R-411B', gwp: 5, kind: 'blend' },
  { key: 'epa_gwp_r_414a_kg', name: 'R-414A', gwp: 0, kind: 'blend' },
  { key: 'epa_gwp_r_414b_kg', name: 'R-414B', gwp: 0, kind: 'blend' },
  { key: 'epa_gwp_r_417a_kg', name: 'R-417A', gwp: 2508, kind: 'blend' },
  { key: 'epa_gwp_r_422a_kg', name: 'R-422A', gwp: 3359, kind: 'blend' },
  { key: 'epa_gwp_r_422b_kg', name: 'R-422B', gwp: 2700, kind: 'blend' },
  { key: 'epa_gwp_r_422c_kg', name: 'R-422C', gwp: 3296, kind: 'blend' },
  { key: 'epa_gwp_r_422d_kg', name: 'R-422D', gwp: 2917, kind: 'blend' },
  { key: 'epa_gwp_r_424a_kg', name: 'R-424A', gwp: 2608, kind: 'blend' },
  { key: 'epa_gwp_r_426a_kg', name: 'R-426A', gwp: 1614, kind: 'blend' },
  { key: 'epa_gwp_r_427a_kg', name: 'R-427A', gwp: 2397, kind: 'blend' },
  { key: 'epa_gwp_r_428a_kg', name: 'R-428A', gwp: 4061, kind: 'blend' },
  { key: 'epa_gwp_r_434a_kg', name: 'R-434A', gwp: 3654, kind: 'blend' },
  { key: 'epa_gwp_r_438a_kg', name: 'R-438A', gwp: 2425, kind: 'blend' },
  { key: 'epa_gwp_r_441a_kg', name: 'R-441A', gwp: 0, kind: 'blend' },
  { key: 'epa_gwp_r_442a_kg', name: 'R-442A', gwp: 2042, kind: 'blend' },
  { key: 'epa_gwp_r_448a_kg', name: 'R-448A', gwp: 1494, kind: 'blend' },
  { key: 'epa_gwp_r_449a_kg', name: 'R-449A', gwp: 1504, kind: 'blend' },
  { key: 'epa_gwp_r_450a_kg', name: 'R-450A', gwp: 643, kind: 'blend' },
  { key: 'epa_gwp_r_507a_kg', name: 'R-507A', gwp: 4775, kind: 'blend' },
  { key: 'epa_gwp_r_508a_kg', name: 'R-508A', gwp: 13258, kind: 'blend' },
  { key: 'epa_gwp_r_508b_kg', name: 'R-508B', gwp: 13412, kind: 'blend' },
  { key: 'epa_gwp_r_513a_kg', name: 'R-513A', gwp: 673, kind: 'blend' },
]

export const EPA_FREIGHT_ROWS: EpaActivityRow[] = [
  { key: 'epa_freight_medium_and_heavy_duty_truck_vehicle_mile', name: 'Medium- and Heavy-Duty Truck (vehicle-mile)', kg: 1.3085753, unit: 'vehicle-mile' },
  { key: 'epa_freight_passenger_car_vehicle_mile', name: 'Passenger Car (vehicle-mile)', kg: 0.2986062, unit: 'vehicle-mile' },
  { key: 'epa_freight_light_duty_truck_vehicle_mile', name: 'Light-Duty Truck (vehicle-mile)', kg: 0.3966967, unit: 'vehicle-mile' },
  { key: 'epa_freight_medium_and_heavy_duty_truck_short_ton_mile', name: 'Medium- and Heavy-Duty Truck (short ton-mile)', kg: 0.1875174, unit: 'short ton-mile' },
  { key: 'epa_freight_rail_short_ton_mile', name: 'Rail (short ton-mile)', kg: 0.0211797, unit: 'short ton-mile' },
  { key: 'epa_freight_waterborne_craft_short_ton_mile', name: 'Waterborne Craft (short ton-mile)', kg: 0.078383, unit: 'short ton-mile' },
  { key: 'epa_freight_aircraft_short_ton_mile', name: 'Aircraft (short ton-mile)', kg: 1.0951182, unit: 'short ton-mile' },
]

export const EPA_TRAVEL_ROWS: EpaActivityRow[] = [
  { key: 'epa_travel_passenger_car', name: 'Passenger Car', kg: 0.2986062, unit: 'vehicle-mile' },
  { key: 'epa_travel_light_duty_truck', name: 'Light-Duty Truck', kg: 0.3966967, unit: 'vehicle-mile' },
  { key: 'epa_travel_motorcycle', name: 'Motorcycle', kg: 0.37553, unit: 'vehicle-mile' },
  { key: 'epa_travel_intercity_rail_northeast_corridor', name: 'Intercity Rail - Northeast Corridor', kg: 0.0230543, unit: 'passenger-mile' },
  { key: 'epa_travel_intercity_rail_other_routes', name: 'Intercity Rail - Other Routes', kg: 0.150416, unit: 'passenger-mile' },
  { key: 'epa_travel_intercity_rail_national_average', name: 'Intercity Rail - National Average', kg: 0.096762, unit: 'passenger-mile' },
  { key: 'epa_travel_commuter_rail', name: 'Commuter Rail', kg: 0.1339933, unit: 'passenger-mile' },
  { key: 'epa_travel_transit_rail_subway_tram', name: 'Transit Rail (subway, tram)', kg: 0.0934755, unit: 'passenger-mile' },
  { key: 'epa_travel_bus', name: 'Bus', kg: 0.0666429, unit: 'passenger-mile' },
  { key: 'epa_travel_air_travel_short_haul_lt_300_miles', name: 'Air Travel - Short Haul (< 300 miles)', kg: 0.2175515, unit: 'passenger-mile' },
  { key: 'epa_travel_air_travel_medium_haul_300_2300_miles', name: 'Air Travel - Medium Haul (300–2300 miles)', kg: 0.121545, unit: 'passenger-mile' },
  { key: 'epa_travel_air_travel_long_haul_gt_2300_miles', name: 'Air Travel - Long Haul (>= 2300 miles)', kg: 0.1451456, unit: 'passenger-mile' },
]

export const EPA_WASTE_ROWS: EpaWasteRow[] = [
  { key: 'epa_waste_aluminum_cans_recycled', material: 'Aluminum Cans', route: 'Recycled', kgPerShortTon: 60 },
  { key: 'epa_waste_aluminum_cans_landfilled', material: 'Aluminum Cans', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_aluminum_cans_combusted', material: 'Aluminum Cans', route: 'Combusted', kgPerShortTon: 10 },
  { key: 'epa_waste_aluminum_ingot_recycled', material: 'Aluminum Ingot', route: 'Recycled', kgPerShortTon: 40 },
  { key: 'epa_waste_aluminum_ingot_landfilled', material: 'Aluminum Ingot', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_aluminum_ingot_combusted', material: 'Aluminum Ingot', route: 'Combusted', kgPerShortTon: 10 },
  { key: 'epa_waste_steel_cans_recycled', material: 'Steel Cans', route: 'Recycled', kgPerShortTon: 320 },
  { key: 'epa_waste_steel_cans_landfilled', material: 'Steel Cans', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_steel_cans_combusted', material: 'Steel Cans', route: 'Combusted', kgPerShortTon: 10 },
  { key: 'epa_waste_copper_wire_recycled', material: 'Copper Wire', route: 'Recycled', kgPerShortTon: 180 },
  { key: 'epa_waste_copper_wire_landfilled', material: 'Copper Wire', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_copper_wire_combusted', material: 'Copper Wire', route: 'Combusted', kgPerShortTon: 10 },
  { key: 'epa_waste_glass_recycled', material: 'Glass', route: 'Recycled', kgPerShortTon: 50 },
  { key: 'epa_waste_glass_landfilled', material: 'Glass', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_glass_combusted', material: 'Glass', route: 'Combusted', kgPerShortTon: 10 },
  { key: 'epa_waste_hdpe_recycled', material: 'HDPE', route: 'Recycled', kgPerShortTon: 210 },
  { key: 'epa_waste_hdpe_landfilled', material: 'HDPE', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_hdpe_combusted', material: 'HDPE', route: 'Combusted', kgPerShortTon: 2800 },
  { key: 'epa_waste_ldpe_landfilled', material: 'LDPE', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_ldpe_combusted', material: 'LDPE', route: 'Combusted', kgPerShortTon: 2800 },
  { key: 'epa_waste_pet_recycled', material: 'PET', route: 'Recycled', kgPerShortTon: 230 },
  { key: 'epa_waste_pet_landfilled', material: 'PET', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_pet_combusted', material: 'PET', route: 'Combusted', kgPerShortTon: 2050 },
  { key: 'epa_waste_lldpe_landfilled', material: 'LLDPE', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_lldpe_combusted', material: 'LLDPE', route: 'Combusted', kgPerShortTon: 2800 },
  { key: 'epa_waste_pp_recycled', material: 'PP', route: 'Recycled', kgPerShortTon: 200 },
  { key: 'epa_waste_pp_landfilled', material: 'PP', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_pp_combusted', material: 'PP', route: 'Combusted', kgPerShortTon: 2800 },
  { key: 'epa_waste_ps_landfilled', material: 'PS', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_ps_combusted', material: 'PS', route: 'Combusted', kgPerShortTon: 3020 },
  { key: 'epa_waste_pvc_landfilled', material: 'PVC', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_pvc_combusted', material: 'PVC', route: 'Combusted', kgPerShortTon: 1260 },
  { key: 'epa_waste_pla_landfilled', material: 'PLA', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_pla_combusted', material: 'PLA', route: 'Combusted', kgPerShortTon: 10 },
  { key: 'epa_waste_pla_composted', material: 'PLA', route: 'Composted', kgPerShortTon: 130 },
  { key: 'epa_waste_corrugated_containers_recycled', material: 'Corrugated Containers', route: 'Recycled', kgPerShortTon: 110 },
  { key: 'epa_waste_corrugated_containers_landfilled', material: 'Corrugated Containers', route: 'Landfilled', kgPerShortTon: 1000 },
  { key: 'epa_waste_corrugated_containers_combusted', material: 'Corrugated Containers', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_magazines_third_class_mail_recycled', material: 'Magazines/Third-class mail', route: 'Recycled', kgPerShortTon: 20 },
  { key: 'epa_waste_magazines_third_class_mail_landfilled', material: 'Magazines/Third-class mail', route: 'Landfilled', kgPerShortTon: 460 },
  { key: 'epa_waste_magazines_third_class_mail_combusted', material: 'Magazines/Third-class mail', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_newspaper_recycled', material: 'Newspaper', route: 'Recycled', kgPerShortTon: 20 },
  { key: 'epa_waste_newspaper_landfilled', material: 'Newspaper', route: 'Landfilled', kgPerShortTon: 390 },
  { key: 'epa_waste_newspaper_combusted', material: 'Newspaper', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_office_paper_recycled', material: 'Office Paper', route: 'Recycled', kgPerShortTon: 20 },
  { key: 'epa_waste_office_paper_landfilled', material: 'Office Paper', route: 'Landfilled', kgPerShortTon: 1410 },
  { key: 'epa_waste_office_paper_combusted', material: 'Office Paper', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_phonebooks_recycled', material: 'Phonebooks', route: 'Recycled', kgPerShortTon: 40 },
  { key: 'epa_waste_phonebooks_landfilled', material: 'Phonebooks', route: 'Landfilled', kgPerShortTon: 390 },
  { key: 'epa_waste_phonebooks_combusted', material: 'Phonebooks', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_textbooks_recycled', material: 'Textbooks', route: 'Recycled', kgPerShortTon: 40 },
  { key: 'epa_waste_textbooks_landfilled', material: 'Textbooks', route: 'Landfilled', kgPerShortTon: 1410 },
  { key: 'epa_waste_textbooks_combusted', material: 'Textbooks', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_dimensional_lumber_landfilled', material: 'Dimensional Lumber', route: 'Landfilled', kgPerShortTon: 170 },
  { key: 'epa_waste_dimensional_lumber_combusted', material: 'Dimensional Lumber', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_medium_density_fiberboard_landfilled', material: 'Medium-density Fiberboard', route: 'Landfilled', kgPerShortTon: 70 },
  { key: 'epa_waste_medium_density_fiberboard_combusted', material: 'Medium-density Fiberboard', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_food_waste_non_meat_landfilled', material: 'Food Waste (non-meat)', route: 'Landfilled', kgPerShortTon: 670 },
  { key: 'epa_waste_food_waste_non_meat_combusted', material: 'Food Waste (non-meat)', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_food_waste_non_meat_composted', material: 'Food Waste (non-meat)', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_food_waste_non_meat_anaerobically_digested_dry', material: 'Food Waste (non-meat)', route: 'Anaerobically digested (dry)', kgPerShortTon: 140 },
  { key: 'epa_waste_food_waste_non_meat_anaerobically_digested_wet', material: 'Food Waste (non-meat)', route: 'Anaerobically digested (wet)', kgPerShortTon: 110 },
  { key: 'epa_waste_food_waste_meat_only_landfilled', material: 'Food Waste (meat only)', route: 'Landfilled', kgPerShortTon: 690 },
  { key: 'epa_waste_food_waste_meat_only_combusted', material: 'Food Waste (meat only)', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_food_waste_meat_only_composted', material: 'Food Waste (meat only)', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_food_waste_meat_only_anaerobically_digested_dry', material: 'Food Waste (meat only)', route: 'Anaerobically digested (dry)', kgPerShortTon: 140 },
  { key: 'epa_waste_food_waste_meat_only_anaerobically_digested_wet', material: 'Food Waste (meat only)', route: 'Anaerobically digested (wet)', kgPerShortTon: 110 },
  { key: 'epa_waste_beef_landfilled', material: 'Beef', route: 'Landfilled', kgPerShortTon: 640 },
  { key: 'epa_waste_beef_combusted', material: 'Beef', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_beef_composted', material: 'Beef', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_beef_anaerobically_digested_dry', material: 'Beef', route: 'Anaerobically digested (dry)', kgPerShortTon: 140 },
  { key: 'epa_waste_beef_anaerobically_digested_wet', material: 'Beef', route: 'Anaerobically digested (wet)', kgPerShortTon: 110 },
  { key: 'epa_waste_poultry_landfilled', material: 'Poultry', route: 'Landfilled', kgPerShortTon: 730 },
  { key: 'epa_waste_poultry_combusted', material: 'Poultry', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_poultry_composted', material: 'Poultry', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_poultry_anaerobically_digested_dry', material: 'Poultry', route: 'Anaerobically digested (dry)', kgPerShortTon: 140 },
  { key: 'epa_waste_poultry_anaerobically_digested_wet', material: 'Poultry', route: 'Anaerobically digested (wet)', kgPerShortTon: 110 },
  { key: 'epa_waste_grains_landfilled', material: 'Grains', route: 'Landfilled', kgPerShortTon: 2060 },
  { key: 'epa_waste_grains_combusted', material: 'Grains', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_grains_composted', material: 'Grains', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_grains_anaerobically_digested_dry', material: 'Grains', route: 'Anaerobically digested (dry)', kgPerShortTon: 140 },
  { key: 'epa_waste_grains_anaerobically_digested_wet', material: 'Grains', route: 'Anaerobically digested (wet)', kgPerShortTon: 110 },
  { key: 'epa_waste_bread_landfilled', material: 'Bread', route: 'Landfilled', kgPerShortTon: 1490 },
  { key: 'epa_waste_bread_combusted', material: 'Bread', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_bread_composted', material: 'Bread', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_bread_anaerobically_digested_dry', material: 'Bread', route: 'Anaerobically digested (dry)', kgPerShortTon: 140 },
  { key: 'epa_waste_bread_anaerobically_digested_wet', material: 'Bread', route: 'Anaerobically digested (wet)', kgPerShortTon: 110 },
  { key: 'epa_waste_fruits_and_vegetables_landfilled', material: 'Fruits and Vegetables', route: 'Landfilled', kgPerShortTon: 280 },
  { key: 'epa_waste_fruits_and_vegetables_combusted', material: 'Fruits and Vegetables', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_fruits_and_vegetables_composted', material: 'Fruits and Vegetables', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_fruits_and_vegetables_anaerobically_digested_dry', material: 'Fruits and Vegetables', route: 'Anaerobically digested (dry)', kgPerShortTon: 140 },
  { key: 'epa_waste_fruits_and_vegetables_anaerobically_digested_wet', material: 'Fruits and Vegetables', route: 'Anaerobically digested (wet)', kgPerShortTon: 110 },
  { key: 'epa_waste_dairy_products_landfilled', material: 'Dairy Products', route: 'Landfilled', kgPerShortTon: 720 },
  { key: 'epa_waste_dairy_products_combusted', material: 'Dairy Products', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_dairy_products_composted', material: 'Dairy Products', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_dairy_products_anaerobically_digested_dry', material: 'Dairy Products', route: 'Anaerobically digested (dry)', kgPerShortTon: 140 },
  { key: 'epa_waste_dairy_products_anaerobically_digested_wet', material: 'Dairy Products', route: 'Anaerobically digested (wet)', kgPerShortTon: 110 },
  { key: 'epa_waste_yard_trimmings_landfilled', material: 'Yard Trimmings', route: 'Landfilled', kgPerShortTon: 360 },
  { key: 'epa_waste_yard_trimmings_combusted', material: 'Yard Trimmings', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_yard_trimmings_composted', material: 'Yard Trimmings', route: 'Composted', kgPerShortTon: 140 },
  { key: 'epa_waste_yard_trimmings_anaerobically_digested_dry', material: 'Yard Trimmings', route: 'Anaerobically digested (dry)', kgPerShortTon: 110 },
  { key: 'epa_waste_grass_landfilled', material: 'Grass', route: 'Landfilled', kgPerShortTon: 280 },
  { key: 'epa_waste_grass_combusted', material: 'Grass', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_grass_composted', material: 'Grass', route: 'Composted', kgPerShortTon: 140 },
  { key: 'epa_waste_grass_anaerobically_digested_dry', material: 'Grass', route: 'Anaerobically digested (dry)', kgPerShortTon: 90 },
  { key: 'epa_waste_leaves_landfilled', material: 'Leaves', route: 'Landfilled', kgPerShortTon: 280 },
  { key: 'epa_waste_leaves_combusted', material: 'Leaves', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_leaves_composted', material: 'Leaves', route: 'Composted', kgPerShortTon: 140 },
  { key: 'epa_waste_leaves_anaerobically_digested_dry', material: 'Leaves', route: 'Anaerobically digested (dry)', kgPerShortTon: 120 },
  { key: 'epa_waste_branches_landfilled', material: 'Branches', route: 'Landfilled', kgPerShortTon: 580 },
  { key: 'epa_waste_branches_combusted', material: 'Branches', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_branches_composted', material: 'Branches', route: 'Composted', kgPerShortTon: 140 },
  { key: 'epa_waste_branches_anaerobically_digested_dry', material: 'Branches', route: 'Anaerobically digested (dry)', kgPerShortTon: 150 },
  { key: 'epa_waste_mixed_paper_general_recycled', material: 'Mixed Paper (general)', route: 'Recycled', kgPerShortTon: 70 },
  { key: 'epa_waste_mixed_paper_general_landfilled', material: 'Mixed Paper (general)', route: 'Landfilled', kgPerShortTon: 890 },
  { key: 'epa_waste_mixed_paper_general_combusted', material: 'Mixed Paper (general)', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_mixed_paper_primarily_residential_recycled', material: 'Mixed Paper (primarily residential)', route: 'Recycled', kgPerShortTon: 70 },
  { key: 'epa_waste_mixed_paper_primarily_residential_landfilled', material: 'Mixed Paper (primarily residential)', route: 'Landfilled', kgPerShortTon: 860 },
  { key: 'epa_waste_mixed_paper_primarily_residential_combusted', material: 'Mixed Paper (primarily residential)', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_mixed_paper_primarily_from_offices_recycled', material: 'Mixed Paper (primarily from offices)', route: 'Recycled', kgPerShortTon: 30 },
  { key: 'epa_waste_mixed_paper_primarily_from_offices_landfilled', material: 'Mixed Paper (primarily from offices)', route: 'Landfilled', kgPerShortTon: 840 },
  { key: 'epa_waste_mixed_paper_primarily_from_offices_combusted', material: 'Mixed Paper (primarily from offices)', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_mixed_metals_recycled', material: 'Mixed Metals', route: 'Recycled', kgPerShortTon: 230 },
  { key: 'epa_waste_mixed_metals_landfilled', material: 'Mixed Metals', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_mixed_metals_combusted', material: 'Mixed Metals', route: 'Combusted', kgPerShortTon: 10 },
  { key: 'epa_waste_mixed_plastics_recycled', material: 'Mixed Plastics', route: 'Recycled', kgPerShortTon: 220 },
  { key: 'epa_waste_mixed_plastics_landfilled', material: 'Mixed Plastics', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_mixed_plastics_combusted', material: 'Mixed Plastics', route: 'Combusted', kgPerShortTon: 2340 },
  { key: 'epa_waste_mixed_recyclables_recycled', material: 'Mixed Recyclables', route: 'Recycled', kgPerShortTon: 90 },
  { key: 'epa_waste_mixed_recyclables_landfilled', material: 'Mixed Recyclables', route: 'Landfilled', kgPerShortTon: 750 },
  { key: 'epa_waste_mixed_recyclables_combusted', material: 'Mixed Recyclables', route: 'Combusted', kgPerShortTon: 110 },
  { key: 'epa_waste_food_waste_landfilled', material: 'Food Waste', route: 'Landfilled', kgPerShortTon: 680 },
  { key: 'epa_waste_food_waste_combusted', material: 'Food Waste', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_food_waste_composted', material: 'Food Waste', route: 'Composted', kgPerShortTon: 110 },
  { key: 'epa_waste_mixed_organics_landfilled', material: 'Mixed Organics', route: 'Landfilled', kgPerShortTon: 540 },
  { key: 'epa_waste_mixed_organics_combusted', material: 'Mixed Organics', route: 'Combusted', kgPerShortTon: 50 },
  { key: 'epa_waste_mixed_organics_composted', material: 'Mixed Organics', route: 'Composted', kgPerShortTon: 130 },
  { key: 'epa_waste_mixed_msw_landfilled', material: 'Mixed MSW', route: 'Landfilled', kgPerShortTon: 580 },
  { key: 'epa_waste_mixed_msw_combusted', material: 'Mixed MSW', route: 'Combusted', kgPerShortTon: 430 },
  { key: 'epa_waste_carpet_landfilled', material: 'Carpet', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_carpet_combusted', material: 'Carpet', route: 'Combusted', kgPerShortTon: 1680 },
  { key: 'epa_waste_desktop_cpus_recycled', material: 'Desktop CPUs', route: 'Recycled', kgPerShortTon: 10 },
  { key: 'epa_waste_desktop_cpus_landfilled', material: 'Desktop CPUs', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_desktop_cpus_combusted', material: 'Desktop CPUs', route: 'Combusted', kgPerShortTon: 400 },
  { key: 'epa_waste_portable_electronic_devices_recycled', material: 'Portable Electronic Devices', route: 'Recycled', kgPerShortTon: 20 },
  { key: 'epa_waste_portable_electronic_devices_landfilled', material: 'Portable Electronic Devices', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_portable_electronic_devices_combusted', material: 'Portable Electronic Devices', route: 'Combusted', kgPerShortTon: 890 },
  { key: 'epa_waste_flat_panel_displays_recycled', material: 'Flat-panel Displays', route: 'Recycled', kgPerShortTon: 20 },
  { key: 'epa_waste_flat_panel_displays_landfilled', material: 'Flat-panel Displays', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_flat_panel_displays_combusted', material: 'Flat-panel Displays', route: 'Combusted', kgPerShortTon: 740 },
  { key: 'epa_waste_crt_displays_landfilled', material: 'CRT Displays', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_crt_displays_combusted', material: 'CRT Displays', route: 'Combusted', kgPerShortTon: 640 },
  { key: 'epa_waste_electronic_peripherals_recycled', material: 'Electronic Peripherals', route: 'Recycled', kgPerShortTon: 50 },
  { key: 'epa_waste_electronic_peripherals_landfilled', material: 'Electronic Peripherals', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_electronic_peripherals_combusted', material: 'Electronic Peripherals', route: 'Combusted', kgPerShortTon: 2230 },
  { key: 'epa_waste_hard_copy_devices_recycled', material: 'Hard-copy Devices', route: 'Recycled', kgPerShortTon: 10 },
  { key: 'epa_waste_hard_copy_devices_landfilled', material: 'Hard-copy Devices', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_hard_copy_devices_combusted', material: 'Hard-copy Devices', route: 'Combusted', kgPerShortTon: 1920 },
  { key: 'epa_waste_mixed_electronics_recycled', material: 'Mixed Electronics', route: 'Recycled', kgPerShortTon: 20 },
  { key: 'epa_waste_mixed_electronics_landfilled', material: 'Mixed Electronics', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_mixed_electronics_combusted', material: 'Mixed Electronics', route: 'Combusted', kgPerShortTon: 960 },
  { key: 'epa_waste_clay_bricks_landfilled', material: 'Clay Bricks', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_concrete_recycled', material: 'Concrete', route: 'Recycled', kgPerShortTon: 10 },
  { key: 'epa_waste_concrete_landfilled', material: 'Concrete', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_fly_ash_recycled', material: 'Fly Ash', route: 'Recycled', kgPerShortTon: 10 },
  { key: 'epa_waste_fly_ash_landfilled', material: 'Fly Ash', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_tires_recycled', material: 'Tires', route: 'Recycled', kgPerShortTon: 100 },
  { key: 'epa_waste_tires_landfilled', material: 'Tires', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_tires_combusted', material: 'Tires', route: 'Combusted', kgPerShortTon: 2210 },
  { key: 'epa_waste_asphalt_concrete_recycled', material: 'Asphalt Concrete', route: 'Recycled', kgPerShortTon: 4 },
  { key: 'epa_waste_asphalt_concrete_landfilled', material: 'Asphalt Concrete', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_asphalt_shingles_recycled', material: 'Asphalt Shingles', route: 'Recycled', kgPerShortTon: 30 },
  { key: 'epa_waste_asphalt_shingles_landfilled', material: 'Asphalt Shingles', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_asphalt_shingles_combusted', material: 'Asphalt Shingles', route: 'Combusted', kgPerShortTon: 700 },
  { key: 'epa_waste_drywall_landfilled', material: 'Drywall', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_fiberglass_insulation_recycled', material: 'Fiberglass Insulation', route: 'Recycled', kgPerShortTon: 50 },
  { key: 'epa_waste_fiberglass_insulation_landfilled', material: 'Fiberglass Insulation', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_structural_steel_recycled', material: 'Structural Steel', route: 'Recycled', kgPerShortTon: 40 },
  { key: 'epa_waste_structural_steel_landfilled', material: 'Structural Steel', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_vinyl_flooring_landfilled', material: 'Vinyl Flooring', route: 'Landfilled', kgPerShortTon: 20 },
  { key: 'epa_waste_vinyl_flooring_combusted', material: 'Vinyl Flooring', route: 'Combusted', kgPerShortTon: 290 },
  { key: 'epa_waste_wood_flooring_landfilled', material: 'Wood Flooring', route: 'Landfilled', kgPerShortTon: 180 },
  { key: 'epa_waste_wood_flooring_combusted', material: 'Wood Flooring', route: 'Combusted', kgPerShortTon: 80 },
]

