import type { EmissionFactor, FactorMethod, Scope, SourceFamily } from './types'
import { buildCedaFactors } from './ceda'
import { buildEpaFactors } from './epa-catalog'
import { buildDesnzDetailFactors } from './desnz-detail'

export const FACTOR_YEAR = '2026'
export const FACTOR_VERIFIED_AT = '2026-09-11'

const YEAR = FACTOR_YEAR
const VERIFIED = FACTOR_VERIFIED_AT
const GOV_URL =
  'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2026'
const SPEND_URL = 'https://www.gov.uk/government/statistics/uks-carbon-footprint'
const IPCC_URL = 'https://www.ipcc.ch/report/ar5/wg1/'
const NPI_URL =
  'https://www.dcceew.gov.au/environment/protection/npi/reporting/industry-reporting-materials/emission-estimation-technique-manuals/emission-estimation-technique-manual-explosives-detonation-and-firing-ranges'

const DEFRA =
  'UK GHG Conversion Factors for Company Reporting 2026 (DESNZ / DEFRA; formerly BEIS). kg CO₂e, IPCC AR5. Published 11 June 2026; flat file revised 31 July 2026. For 2026 activity / SECR 2026.'
const DESNZ =
  'UK GHG Conversion Factors for Company Reporting 2026 — electricity / heat (DESNZ). kg CO₂e, IPCC AR5. Published 11 June 2026; flat file revised 31 July 2026. For 2026 activity / SECR 2026.'
const IPCC =
  'IPCC Fifth Assessment Report (AR5) Working Group I, 100-year GWP without climate-carbon feedbacks. Methane GWP = 28. DESNZ 2026 refrigerants still use AR5, so mine methane stays on AR5 for consistency. EPA Hub 2026 publishes fossil methane GWP 29.8 as mine_ch4_epa_fossil_kg.'
const NPI =
  'Australian National Pollutant Inventory Emission Estimation Technique Manual for Explosives Detonation and Firing Ranges v3.1 (August 2016). Mass-balance combustion CO₂. NGER Measurement Determination has no Method 1 look-up table for detonation. Prefer a manufacturer or site-specific factor when available.'
const EIO =
  'Defra spend-based emissions multipliers, 1997 to 2023 (published 30 June 2026), SIC-19 current-price GHG multipliers (kg CO₂e per £). Catalogue stores the published kg CO₂e per pound. tCO₂e = £ spent × kg/£ ÷ 1,000. Use only when activity data is unavailable. Open CEDA by Watershed (CEDA 2025) is a separate USD EEIO family — do not mix £ and $.'

type FactorExtras = {
  method?: FactorMethod
  wttKey?: string
  tdKey?: string
  evKey?: string
  evTdKey?: string
}

function factor(
  key: string,
  name: string,
  category: string,
  scope: Scope,
  conversionValue: number,
  unit: string,
  sourceFamily: SourceFamily,
  source: string,
  sourceUrl: string,
  extras: FactorExtras = {},
): EmissionFactor {
  return {
    key,
    name,
    category,
    scope,
    conversionValue,
    unit,
    sourceFamily,
    source,
    sourceUrl,
    region: 'United Kingdom',
    validFrom: `${YEAR}-01-01`,
    lastVerifiedAt: VERIFIED,
    isPlaceholder: false,
    ...extras,
  }
}

const HOTEL_COUNTRIES: Array<[string, string, number]> = [
  ['UK (London)', 'hotel_london_night', 11.5],
  ['Australia', 'hotel_australia_night', 35],
  ['Belgium', 'hotel_belgium_night', 12.2],
  ['Brazil', 'hotel_brazil_night', 8.7],
  ['Canada', 'hotel_canada_night', 7.4],
  ['Chile', 'hotel_chile_night', 27.6],
  ['China', 'hotel_china_night', 53.5],
  ['Colombia', 'hotel_colombia_night', 14.7],
  ['Costa Rica', 'hotel_costa_rica_night', 4.7],
  ['Egypt', 'hotel_egypt_night', 44.2],
  ['France', 'hotel_france_night', 6.7],
  ['Germany', 'hotel_germany_night', 13.2],
  ['Hong Kong, China', 'hotel_hong_kong_night', 51.5],
  ['India', 'hotel_india_night', 58.9],
  ['Indonesia', 'hotel_indonesia_night', 62.7],
  ['Italy', 'hotel_italy_night', 14.3],
  ['Japan', 'hotel_japan_night', 39],
  ['Jordan', 'hotel_jordan_night', 68.9],
  ['Korea', 'hotel_korea_night', 55.8],
  ['Malaysia', 'hotel_malaysia_night', 61.5],
  ['Maldives', 'hotel_maldives_night', 152.2],
  ['Mexico', 'hotel_mexico_night', 19.3],
  ['Netherlands', 'hotel_netherlands_night', 14.8],
  ['Oman', 'hotel_oman_night', 90.3],
  ['Philippines', 'hotel_philippines_night', 54.3],
  ['Portugal', 'hotel_portugal_night', 19],
  ['Qatar', 'hotel_qatar_night', 86.2],
  ['Russian Federation', 'hotel_russia_night', 24.2],
  ['Saudi Arabia', 'hotel_saudi_night', 106.4],
  ['Singapore', 'hotel_singapore_night', 24.5],
  ['South Africa', 'hotel_south_africa_night', 51.4],
  ['Spain', 'hotel_spain_night', 7],
  ['Switzerland', 'hotel_switzerland_night', 6.6],
  ['Thailand', 'hotel_thailand_night', 43.4],
  ['Turkey', 'hotel_turkey_night', 32.1],
  ['United Arab Emirates', 'hotel_uae_night', 63.8],
  ['United States', 'hotel_usa_night', 16.1],
  ['Vietnam', 'hotel_vietnam_night', 38.5],
]

const HOTEL_COUNTRY_FACTORS = HOTEL_COUNTRIES.map(([country, key, kg]) =>
  factor(
    key,
    `Hotel stay (${country})`,
    'Business travel',
    'Scope 3',
    kg,
    'night',
    'DEFRA',
    `${DEFRA} Hotel stay — ${country}, per room per night. tCO₂e = room-nights × ${kg} ÷ 1,000.`,
    GOV_URL,
  ),
)

export const HOTEL_COUNTRY_OPTIONS = ['UK', ...HOTEL_COUNTRIES.map(([country]) => country)]

export function hotelFactorKey(country: string) {
  if (!country || country === 'UK') return 'hotel_uk_night'
  const row = HOTEL_COUNTRIES.find(([name]) => name === country)
  return row?.[1] ?? 'hotel_uk_night'
}

function firstByKey(rows: EmissionFactor[]): EmissionFactor[] {
  const seen = new Set<string>()
  const out: EmissionFactor[] = []
  for (const row of rows) {
    if (seen.has(row.key)) continue
    seen.add(row.key)
    out.push(row)
  }
  return out
}

export const FACTOR_CATALOG: EmissionFactor[] = firstByKey([
  factor(
    'electricity_grid_kwh',
    'UK grid electricity (generated)',
    'Site energy',
    'Scope 2',
    0.13096,
    'kWh',
    'DESNZ',
    `${DESNZ} UK electricity / Electricity generated / Electricity: UK. tCO₂e = kWh × 0.13096 ÷ 1,000. Also log T&D (electricity_td_kwh) and WTT generation (wtt_electricity_kwh) for a complete energy chain.`,
    GOV_URL,
    { wttKey: 'wtt_electricity_kwh', tdKey: 'electricity_td_kwh' },
  ),
  factor(
    'electricity_renewable_kwh',
    'On-site renewable electricity',
    'Site energy',
    'Scope 2',
    0,
    'kWh',
    'DESNZ',
    `${DESNZ} Location-based residual for on-site generation (no grid factor).`,
    GOV_URL,
  ),
  factor(
    'electricity_td_kwh',
    'UK electricity T&D losses',
    'Site energy',
    'Scope 3',
    0.01299,
    'kWh',
    'DESNZ',
    `${DESNZ} Transmission and distribution / T&D- UK electricity.`,
    GOV_URL,
  ),
  factor(
    'heat_steam_kwh',
    'District / onsite heat and steam',
    'Site energy',
    'Scope 2',
    0.17529,
    'kWh',
    'DESNZ',
    `${DESNZ} Heat and steam / Onsite or District heat and steam.`,
    GOV_URL,
    { tdKey: 'heat_td_kwh' },
  ),
  factor(
    'natural_gas_kwh',
    'Natural gas (gross CV)',
    'Site fuel',
    'Scope 1',
    0.18231,
    'kWh',
    'DEFRA',
    `${DEFRA} Fuels — natural gas, kWh (Gross CV).`,
    GOV_URL,
    { wttKey: 'wtt_natural_gas_kwh' },
  ),
  factor(
    'natural_gas_m3',
    'Natural gas',
    'Site fuel',
    'Scope 1',
    2.02633,
    'm³',
    'DEFRA',
    `${DEFRA} Fuels — natural gas, cubic metres.`,
    GOV_URL,
  ),
  factor(
    'diesel_litre',
    'Diesel (average biofuel blend)',
    'Site fuel',
    'Scope 1',
    2.58354,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — diesel (average biofuel blend), litres.`,
    GOV_URL,
    { wttKey: 'wtt_diesel_litre' },
  ),
  factor(
    'petrol_litre',
    'Petrol (average biofuel blend)',
    'Site fuel',
    'Scope 1',
    2.075,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — petrol (average biofuel blend), litres.`,
    GOV_URL,
    { wttKey: 'wtt_petrol_litre' },
  ),
  factor(
    'lpg_litre',
    'LPG',
    'Site fuel',
    'Scope 1',
    1.55713,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — LPG, litres.`,
    GOV_URL,
    { wttKey: 'wtt_lpg_litre' },
  ),
  factor(
    'hvo_litre',
    'HVO / renewable diesel',
    'Site fuel',
    'Scope 1',
    0.03558,
    'L',
    'DEFRA',
    `${DEFRA} Bioenergy — biodiesel HVO, litres. Scope 1 CH₄/N₂O only.`,
    GOV_URL,
  ),
  factor(
    'gas_oil_litre',
    'Red diesel / gas oil (plant)',
    'Heavy machinery',
    'Scope 1',
    2.75541,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — gas oil, litres.`,
    GOV_URL,
    { wttKey: 'wtt_gas_oil_litre' },
  ),
  factor(
    'marine_gas_oil_litre',
    'Marine gas oil',
    'Sea freight',
    'Scope 1',
    2.77139,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — marine gas oil, litres.`,
    GOV_URL,
  ),
  factor(
    'aviation_turbine_litre',
    'Aviation turbine fuel',
    'Air freight',
    'Scope 1',
    2.54269,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — aviation turbine fuel, litres.`,
    GOV_URL,
  ),
  factor(
    'r404a_kg',
    'R-404A refrigerant',
    'Refrigerants',
    'Scope 1',
    3943,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of R-404A (Kyoto products, IPCC AR5). tCO₂e = kg leaked × GWP ÷ 1,000.`,
    GOV_URL,
    { method: 'gwp' },
  ),
  factor(
    'r410a_kg',
    'R-410A refrigerant',
    'Refrigerants',
    'Scope 1',
    1924,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of R-410A (Kyoto products, IPCC AR5). tCO₂e = kg leaked × GWP ÷ 1,000.`,
    GOV_URL,
    { method: 'gwp' },
  ),
  factor(
    'r134a_kg',
    'HFC-134a refrigerant',
    'Refrigerants',
    'Scope 1',
    1300,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of HFC-134a (Kyoto products, IPCC AR5). tCO₂e = kg leaked × GWP ÷ 1,000.`,
    GOV_URL,
    { method: 'gwp' },
  ),
  factor(
    'co2_kg',
    'Carbon dioxide refrigerant',
    'Refrigerants',
    'Scope 1',
    1,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of CO₂. tCO₂e = kg leaked × 1 ÷ 1,000.`,
    GOV_URL,
    { method: 'gwp' },
  ),
  factor(
    'freight_road_tkm',
    'Road freight (average non-refrigerated HGVs, average laden)',
    'Road freight',
    'Scope 3',
    0.10356,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — average non-refrigerated HGVs, average laden. 2026 no longer publishes a combined “all HGVs” row.`,
    GOV_URL,
  ),
  factor(
    'freight_rail_tkm',
    'Rail freight',
    'Rail freight',
    'Scope 3',
    0.02583,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — freight train.`,
    GOV_URL,
  ),
  factor(
    'freight_sea_tkm',
    'Sea freight (container ship, average)',
    'Sea freight',
    'Scope 3',
    0.01612,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — cargo ship, container, average.`,
    GOV_URL,
  ),
  factor(
    'freight_air_tkm',
    'Air freight (short-haul, with RF)',
    'Air freight',
    'Scope 3',
    1.27835,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — freight flights, short-haul, with radiative forcing (the DESNZ default air row). Without RF is freight_air_tkm_no_rf (0.75539). tCO₂e = tonnes × km × factor ÷ 1,000.`,
    GOV_URL,
  ),
  factor(
    'waste_landfill_kg',
    'Construction waste to landfill',
    'Waste',
    'Scope 3',
    1.27043,
    't',
    'DEFRA',
    `${DEFRA} Waste disposal — construction aggregates/asphalt/concrete/bricks landfill. Published as 1.27043 kg CO₂e per tonne, not per kg. Convert kg to tonnes first, then tCO₂e = tonnes × 1.27043 ÷ 1,000.`,
    GOV_URL,
  ),
  factor(
    'waste_recycling_kg',
    'Construction waste recycled',
    'Waste',
    'Scope 3',
    1.01398,
    't',
    'DEFRA',
    `${DEFRA} Waste disposal — construction closed-loop / open-loop recycling. Published as 1.01398 kg CO₂e per tonne.`,
    GOV_URL,
  ),
  factor(
    'waste_combustion_kg',
    'Construction waste combusted / energy recovery',
    'Waste',
    'Scope 3',
    4.65358,
    't',
    'DEFRA',
    `${DEFRA} Waste disposal — average construction, combustion. Published as 4.65358 kg CO₂e per tonne. Use for energy recovery; do not use the landfill row (1.27043).`,
    GOV_URL,
  ),
  factor(
    'water_m3',
    'Mains water supply',
    'Water',
    'Scope 3',
    0.1913,
    'm³',
    'DEFRA',
    `${DEFRA} Water supply.`,
    GOV_URL,
  ),
  factor(
    'crew_van_km',
    'Average car (unknown fuel)',
    'Crew transport',
    'Scope 3',
    0.16591,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average car, unknown fuel.`,
    GOV_URL,
  ),
  factor(
    'crew_bus_pkm',
    'Average local bus',
    'Crew transport',
    'Scope 3',
    0.10151,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — average local bus.`,
    GOV_URL,
  ),
  factor(
    'crew_rail_pkm',
    'National rail',
    'Crew transport',
    'Scope 3',
    0.03092,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — national rail.`,
    GOV_URL,
  ),
  factor(
    'material_concrete_t',
    'Concrete (primary production)',
    'Bulk materials',
    'Scope 3',
    118.80307,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction concrete, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_timber_t',
    'Wood (primary production)',
    'Bulk materials',
    'Scope 3',
    269.50416,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction wood, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_asphalt_t',
    'Asphalt (primary production)',
    'Bulk materials',
    'Scope 3',
    39.21249,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction asphalt, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_aggregates_t',
    'Aggregates (primary production)',
    'Bulk materials',
    'Scope 3',
    7.80307,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction aggregates, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_metals_t',
    'Construction metals (primary production)',
    'Bulk materials',
    'Scope 3',
    3821.94858,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction metals, primary material production (mixed metals, not section steel).`,
    GOV_URL,
  ),

  // ── Well-to-tank (WTT) factors ──────────────────────────────────────────
  factor(
    'wtt_diesel_litre',
    'WTT — diesel',
    'WTT fuels',
    'Scope 3',
    0.61101,
    'L',
    'DEFRA',
    `${DEFRA} WTT-fuels — diesel (average biofuel blend), litres.`,
    GOV_URL,
  ),
  factor(
    'wtt_petrol_litre',
    'WTT — petrol',
    'WTT fuels',
    'Scope 3',
    0.58094,
    'L',
    'DEFRA',
    `${DEFRA} WTT-fuels — petrol (average biofuel blend), litres.`,
    GOV_URL,
  ),
  factor(
    'wtt_lpg_litre',
    'WTT — LPG',
    'WTT fuels',
    'Scope 3',
    0.18551,
    'L',
    'DEFRA',
    `${DEFRA} WTT-fuels — LPG, litres.`,
    GOV_URL,
  ),
  factor(
    'wtt_gas_oil_litre',
    'WTT — gas oil',
    'WTT fuels',
    'Scope 3',
    0.62665,
    'L',
    'DEFRA',
    `${DEFRA} WTT-fuels — gas oil, litres.`,
    GOV_URL,
  ),
  factor(
    'wtt_natural_gas_kwh',
    'WTT — natural gas',
    'WTT fuels',
    'Scope 3',
    0.03021,
    'kWh',
    'DEFRA',
    `${DEFRA} WTT-fuels — natural gas, kWh (Gross CV), to match the combustion Gross CV factor.`,
    GOV_URL,
  ),
  factor(
    'wtt_electricity_kwh',
    'WTT — UK grid electricity (generation)',
    'WTT energy',
    'Scope 3',
    0.03682,
    'kWh',
    'DESNZ',
    `${DESNZ} WTT- UK electricity (generation). Transmission and distribution stays on electricity_td_kwh.`,
    GOV_URL,
  ),

  // ── Business travel: flights ────────────────────────────────────────────
  factor(
    'flight_domestic_pkm',
    'Domestic flights',
    'Business travel',
    'Scope 3',
    0.22928,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–air — domestic, average passenger, with RF.`,
    GOV_URL,
  ),
  factor(
    'flight_shorthaul_pkm',
    'Short-haul flights (economy)',
    'Business travel',
    'Scope 3',
    0.12576,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–air — short-haul, economy class, with RF.`,
    GOV_URL,
  ),
  factor(
    'flight_longhaul_economy_pkm',
    'Long-haul flights (economy)',
    'Business travel',
    'Scope 3',
    0.11704,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–air — long-haul, economy class, with RF.`,
    GOV_URL,
  ),
  factor(
    'flight_longhaul_business_pkm',
    'Long-haul flights (business)',
    'Business travel',
    'Scope 3',
    0.3394,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–air — long-haul, business class, with RF.`,
    GOV_URL,
  ),

  // ── Business travel: hotel nights ───────────────────────────────────────
  factor(
    'hotel_uk_night',
    'Hotel stay (UK)',
    'Business travel',
    'Scope 3',
    10.4,
    'night',
    'DEFRA',
    `${DEFRA} Hotel stay — UK, per room per night.`,
    GOV_URL,
  ),
  ...HOTEL_COUNTRY_FACTORS,

  // ── Business travel: land / taxis ───────────────────────────────────────
  factor(
    'taxi_pkm',
    'Regular taxi',
    'Business travel',
    'Scope 3',
    0.14861,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — regular taxi, kg CO₂e per passenger.km. tCO₂e = passengers × km × 0.14861 ÷ 1,000. The vehicle-km row (0.20806) is taxi_km.`,
    GOV_URL,
  ),
  factor(
    'taxi_km',
    'Regular taxi (vehicle-km)',
    'Business travel',
    'Scope 3',
    0.20806,
    'km',
    'DEFRA',
    `${DEFRA} Business travel–land — regular taxi, kg CO₂e per vehicle-km. Use only when you do not know passenger count.`,
    GOV_URL,
  ),

  // ── Employee commuting ──────────────────────────────────────────────────
  factor(
    'commute_car_km',
    'Average car (commuting)',
    'Employee commuting',
    'Scope 3',
    0.16591,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average car, unknown fuel.`,
    GOV_URL,
  ),
  factor(
    'commute_bus_pkm',
    'Average local bus (commuting)',
    'Employee commuting',
    'Scope 3',
    0.10151,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — average local bus.`,
    GOV_URL,
  ),
  factor(
    'commute_rail_pkm',
    'National rail (commuting)',
    'Employee commuting',
    'Scope 3',
    0.03092,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — national rail.`,
    GOV_URL,
  ),
  factor(
    'commute_motorbike_km',
    'Average motorbike (commuting)',
    'Employee commuting',
    'Scope 3',
    0.11367,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average motorbike.`,
    GOV_URL,
  ),

  // ── Wastewater ──────────────────────────────────────────────────────────
  factor(
    'wastewater_m3',
    'Wastewater treatment',
    'Wastewater',
    'Scope 3',
    0.17088,
    'm³',
    'DEFRA',
    `${DEFRA} Water treatment.`,
    GOV_URL,
  ),

  // ── Purchased goods — spend-based (EEIO) ────────────────────────────────
  factor(
    'purchased_goods_gbp',
    'Purchased goods & services (UK average)',
    'Purchased goods',
    'Scope 3',
    0.8559280439858236,
    '£',
    'EIO',
    `${EIO} Unweighted mean of the 18 non-zero SIC-19 GHG multipliers (Construction is published as ~0 and is excluded). tCO₂e = £ spent × 0.8559 ÷ 1,000.`,
    SPEND_URL,
  ),
  factor(
    'capital_goods_gbp',
    'Capital goods (UK average)',
    'Capital goods',
    'Scope 3',
    0.6987898127964011,
    '£',
    'EIO',
    `${EIO} SIC C Manufacturing. tCO₂e = £ spent × 0.6988 ÷ 1,000.`,
    SPEND_URL,
  ),

  // ── Additional construction materials ───────────────────────────────────
  factor(
    'material_glass_t',
    'Glass (primary production)',
    'Bulk materials',
    'Scope 3',
    1402.76667,
    't',
    'DEFRA',
    `${DEFRA} Material use — other / glass, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_bricks_t',
    'Bricks (generic)',
    'Bulk materials',
    'Scope 3',
    241.80307,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction bricks, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_insulation_t',
    'Insulation (general)',
    'Bulk materials',
    'Scope 3',
    1861.80307,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction insulation, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_plasterboard_t',
    'Plasterboard',
    'Bulk materials',
    'Scope 3',
    120.05,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction plasterboard, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_pvc_t',
    'PVC pipe / general',
    'Bulk materials',
    'Scope 3',
    2942.43735,
    't',
    'DEFRA',
    `${DEFRA} Material use — plastics: PVC (incl. forming), primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_soil_t',
    'Soil / earthworks',
    'Bulk materials',
    'Scope 3',
    0,
    't',
    'DEFRA',
    `${DEFRA} Material use — soils primary production is no longer published in 2026 (cell withdrawn). Conversion is 0 rather than an invented replacement. Prefer a site-specific or EPD factor.`,
    GOV_URL,
  ),

  // ── Mining: explosives (Scope 1 combustion) and fugitive methane ────────
  factor(
    'explosives_anfo_kg',
    'ANFO explosives (combustion)',
    'Explosives',
    'Scope 1',
    0.22,
    'kg',
    'EPA',
    `${NPI} ANFO ≈ 0.22 kg CO₂e/kg explosive (≈6% fuel oil, complete oxidation of fuel carbon). Covers blast CO₂, not manufactured embodied carbon.`,
    NPI_URL,
  ),
  factor(
    'explosives_emulsion_kg',
    'Emulsion explosives (combustion)',
    'Explosives',
    'Scope 1',
    0.14,
    'kg',
    'EPA',
    `${NPI} Emulsion blasting agent ≈ 0.14 kg CO₂e/kg explosive, reflecting lower hydrocarbon fuel content.`,
    NPI_URL,
  ),
  factor(
    'mine_ch4_t',
    'Mine methane (tonnes CH₄)',
    'Mine gas',
    'Scope 1',
    28000,
    't',
    'IPCC',
    `${IPCC} 1 t CH₄ × GWP 28 = 28 tCO₂e. tCO₂e = tonnes CH₄ × 28,000 ÷ 1,000.`,
    IPCC_URL,
    { method: 'gwp' },
  ),
  factor(
    'mine_ch4_kg',
    'Mine methane (kg CH₄)',
    'Mine gas',
    'Scope 1',
    28,
    'kg',
    'IPCC',
    `${IPCC} 1 kg CH₄ × GWP 28 = 28 kg CO₂e. tCO₂e = kg CH₄ × 28 ÷ 1,000.`,
    IPCC_URL,
    { method: 'gwp' },
  ),
  factor(
    'mine_ch4_m3',
    'Mine methane (m³ CH₄)',
    'Mine gas',
    'Scope 1',
    20.08,
    'm³',
    'IPCC',
    `${IPCC} CH₄ density 0.717 kg/m³ at 0 °C, 1 atm × GWP 28 ≈ 20.08 kg CO₂e/m³. Convert ventilation air to CH₄ first, then tCO₂e = m³ CH₄ × 20.08 ÷ 1,000.`,
    IPCC_URL,
    { method: 'gwp' },
  ),

  factor(
    'wtt_electricity_td_kwh',
    'WTT — UK electricity T&D',
    'WTT energy',
    'Scope 3',
    0.00359,
    'kWh',
    'DESNZ',
    `${DESNZ} WTT- UK electricity (T&D). Separate from T&D losses (electricity_td_kwh = 0.01299) and WTT generation (0.03682).`,
    GOV_URL,
  ),
  factor(
    'heat_td_kwh',
    'District heat and steam distribution losses (5%)',
    'Heat and steam',
    'Scope 3',
    0.00945,
    'kWh',
    'DESNZ',
    `${DESNZ} Distribution - district heat & steam, 5% loss.`,
    GOV_URL,
  ),
  factor(
    'freight_road_rigid_tkm',
    'Road freight (average non-refrigerated rigids)',
    'Road freight',
    'Scope 3',
    0.19947,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — average non-refrigerated rigids, average laden.`,
    GOV_URL,
  ),
  factor(
    'freight_road_artic_tkm',
    'Road freight (average non-refrigerated artics)',
    'Road freight',
    'Scope 3',
    0.07926,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — average non-refrigerated artics, average laden.`,
    GOV_URL,
  ),
  factor(
    'freight_van_tkm',
    'Van freight (average up to 3.5 t)',
    'Road freight',
    'Scope 3',
    0.63511,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — vans, average (up to 3.5 tonnes).`,
    GOV_URL,
  ),
  factor(
    'freight_sea_bulk_tkm',
    'Sea freight (bulk carrier, average)',
    'Sea freight',
    'Scope 3',
    0.00353,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — cargo ship, bulk carrier, average.`,
    GOV_URL,
  ),
  factor(
    'freight_sea_roro_tkm',
    'Sea freight (RoRo ferry, average)',
    'Sea freight',
    'Scope 3',
    0.05158,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — cargo ship, RoRo-Ferry, average.`,
    GOV_URL,
  ),
  factor(
    'freight_air_tkm_no_rf',
    'Air freight (short-haul, without RF)',
    'Air freight',
    'Scope 3',
    0.75539,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — freight flights, short-haul, without radiative forcing.`,
    GOV_URL,
  ),
  factor(
    'car_diesel_km',
    'Average car (diesel)',
    'Passenger vehicles',
    'Scope 3',
    0.17265,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average car, diesel.`,
    GOV_URL,
  ),
  factor(
    'car_petrol_km',
    'Average car (petrol)',
    'Passenger vehicles',
    'Scope 3',
    0.16152,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average car, petrol.`,
    GOV_URL,
  ),

  ...buildDesnzDetailFactors({ year: YEAR, verifiedAt: VERIFIED }),
  ...buildCedaFactors({ year: YEAR, verifiedAt: VERIFIED }),
  ...buildEpaFactors({ year: YEAR, verifiedAt: VERIFIED }),
])

export const PLACEHOLDER_FACTORS = FACTOR_CATALOG
