import type { EmissionFactor, Scope, SourceFamily } from './types'

export const FACTOR_YEAR = '2026'
export const FACTOR_VERIFIED_AT = '2026-09-10'

const YEAR = FACTOR_YEAR
const VERIFIED = FACTOR_VERIFIED_AT
const GOV_URL =
  'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2026'
const SPEND_URL = 'https://www.gov.uk/government/statistics/uks-carbon-footprint'
const ICE_URL = 'https://circularecology.com/embodied-carbon-footprint-database.html'
const IPCC_URL = 'https://www.ipcc.ch/report/ar5/wg1/'
const NPI_URL =
  'https://www.dcceew.gov.au/environment/protection/npi/reporting/industry-reporting-materials/emission-estimation-technique-manuals/emission-estimation-technique-manual-explosives-detonation-and-firing-ranges'

const DEFRA =
  'UK GHG Conversion Factors for Company Reporting 2026 (DESNZ / DEFRA; formerly BEIS). kg CO₂e, IPCC AR5. Published 11 June 2026; flat file revised 31 July 2026. For 2026 activity / SECR 2026.'
const DESNZ =
  'UK GHG Conversion Factors for Company Reporting 2026 — electricity / heat (DESNZ). kg CO₂e, IPCC AR5. Published 11 June 2026; flat file revised 31 July 2026. For 2026 activity / SECR 2026.'
const ICE =
  'Inventory of Carbon and Energy (ICE) Database v4.1, Circular Ecology (29 October 2025). Cradle-to-gate A1–A3, kg CO₂e per kg converted to per tonne. Used only where DESNZ 2026 has no equivalent material row. ICE Educational v5.0 is education-only after 30 September 2026.'
const IPCC =
  'IPCC Fifth Assessment Report (AR5) Working Group I, 100-year GWP without climate-carbon feedbacks. Methane GWP = 28. DESNZ 2026 refrigerants still use AR5, so mine methane stays on AR5 for consistency.'
const NPI =
  'Australian National Pollutant Inventory Emission Estimation Technique Manual for Explosives Detonation and Firing Ranges v3.1 (August 2016). Mass-balance combustion CO₂. NGER Measurement Determination has no Method 1 look-up table for detonation. Prefer a manufacturer or site-specific factor when available.'
const EIO =
  'Defra spend-based emissions multipliers, 1997 to 2023 (published 30 June 2026), SIC-19 current-price GHG multipliers (kg CO₂e per £). Converted to kg CO₂e per £1,000 so the catalogue unit £k matches tCO₂e = (activity × conversion) / 1000. Use only when activity data is unavailable.'

function factor(
  key: string,
  name: string,
  category: string,
  scope: Scope,
  conversionValue: number,
  unit: string,
  sourceFamily: SourceFamily,
  source: string,
  sourceUrl: string,
): EmissionFactor {
  return {
    key,
    name,
    category,
    scope,
    conversionValue,
    unit,
    sourceFamily,
    source,
    sourceUrl,
    region: 'United Kingdom',
    validFrom: `${YEAR}-01-01`,
    lastVerifiedAt: VERIFIED,
    isPlaceholder: false,
  }
}

export const FACTOR_CATALOG: EmissionFactor[] = [
  factor(
    'electricity_grid_kwh',
    'UK grid electricity (generated)',
    'Site energy',
    'Scope 2',
    0.13096,
    'kWh',
    'DESNZ',
    `${DESNZ} UK electricity / Electricity generated / Electricity: UK.`,
    GOV_URL,
  ),
  factor(
    'electricity_renewable_kwh',
    'On-site renewable electricity',
    'Site energy',
    'Scope 2',
    0,
    'kWh',
    'DESNZ',
    `${DESNZ} Location-based residual for on-site generation (no grid factor).`,
    GOV_URL,
  ),
  factor(
    'electricity_td_kwh',
    'UK electricity T&D losses',
    'Site energy',
    'Scope 3',
    0.01299,
    'kWh',
    'DESNZ',
    `${DESNZ} Transmission and distribution / T&D- UK electricity.`,
    GOV_URL,
  ),
  factor(
    'heat_steam_kwh',
    'District / onsite heat and steam',
    'Site energy',
    'Scope 2',
    0.17529,
    'kWh',
    'DESNZ',
    `${DESNZ} Heat and steam / Onsite or District heat and steam.`,
    GOV_URL,
  ),
  factor(
    'natural_gas_kwh',
    'Natural gas (gross CV)',
    'Site fuel',
    'Scope 1',
    0.18231,
    'kWh',
    'DEFRA',
    `${DEFRA} Fuels — natural gas, kWh (Gross CV).`,
    GOV_URL,
  ),
  factor(
    'natural_gas_m3',
    'Natural gas',
    'Site fuel',
    'Scope 1',
    2.02633,
    'm³',
    'DEFRA',
    `${DEFRA} Fuels — natural gas, cubic metres.`,
    GOV_URL,
  ),
  factor(
    'diesel_litre',
    'Diesel (average biofuel blend)',
    'Site fuel',
    'Scope 1',
    2.58354,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — diesel (average biofuel blend), litres.`,
    GOV_URL,
  ),
  factor(
    'petrol_litre',
    'Petrol (average biofuel blend)',
    'Site fuel',
    'Scope 1',
    2.075,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — petrol (average biofuel blend), litres.`,
    GOV_URL,
  ),
  factor(
    'lpg_litre',
    'LPG',
    'Site fuel',
    'Scope 1',
    1.55713,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — LPG, litres.`,
    GOV_URL,
  ),
  factor(
    'hvo_litre',
    'HVO / renewable diesel',
    'Site fuel',
    'Scope 1',
    0.03558,
    'L',
    'DEFRA',
    `${DEFRA} Bioenergy — biodiesel HVO, litres. Scope 1 CH₄/N₂O only.`,
    GOV_URL,
  ),
  factor(
    'gas_oil_litre',
    'Red diesel / gas oil (plant)',
    'Heavy machinery',
    'Scope 1',
    2.75541,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — gas oil, litres.`,
    GOV_URL,
  ),
  factor(
    'marine_gas_oil_litre',
    'Marine gas oil',
    'Sea freight',
    'Scope 1',
    2.77139,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — marine gas oil, litres.`,
    GOV_URL,
  ),
  factor(
    'aviation_turbine_litre',
    'Aviation turbine fuel',
    'Air freight',
    'Scope 1',
    2.54269,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — aviation turbine fuel, litres.`,
    GOV_URL,
  ),
  factor(
    'r404a_kg',
    'R-404A refrigerant',
    'Refrigerants',
    'Scope 1',
    3943,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of R-404A (Kyoto products, IPCC AR5).`,
    GOV_URL,
  ),
  factor(
    'r410a_kg',
    'R-410A refrigerant',
    'Refrigerants',
    'Scope 1',
    1924,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of R-410A (Kyoto products, IPCC AR5).`,
    GOV_URL,
  ),
  factor(
    'r134a_kg',
    'HFC-134a refrigerant',
    'Refrigerants',
    'Scope 1',
    1300,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of HFC-134a (Kyoto products, IPCC AR5).`,
    GOV_URL,
  ),
  factor(
    'co2_kg',
    'Carbon dioxide refrigerant',
    'Refrigerants',
    'Scope 1',
    1,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of CO₂.`,
    GOV_URL,
  ),
  factor(
    'freight_road_tkm',
    'Road freight (average non-refrigerated HGVs, average laden)',
    'Road freight',
    'Scope 3',
    0.10356,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — average non-refrigerated HGVs, average laden. 2026 no longer publishes a combined “all HGVs” row.`,
    GOV_URL,
  ),
  factor(
    'freight_rail_tkm',
    'Rail freight',
    'Rail freight',
    'Scope 3',
    0.02583,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — freight train.`,
    GOV_URL,
  ),
  factor(
    'freight_sea_tkm',
    'Sea freight (container ship, average)',
    'Sea freight',
    'Scope 3',
    0.01612,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — cargo ship, container, average.`,
    GOV_URL,
  ),
  factor(
    'freight_air_tkm',
    'Air freight (short-haul, without RF)',
    'Air freight',
    'Scope 3',
    0.75539,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — freight flights, short-haul, without radiative forcing.`,
    GOV_URL,
  ),
  factor(
    'waste_landfill_kg',
    'Construction waste to landfill',
    'Waste',
    'Scope 3',
    0.00127043,
    'kg',
    'DEFRA',
    `${DEFRA} Waste disposal — construction aggregates/asphalt/concrete/bricks landfill, 1.27043 kg CO₂e/tonne.`,
    GOV_URL,
  ),
  factor(
    'waste_recycling_kg',
    'Construction waste recycled',
    'Waste',
    'Scope 3',
    0.00101398,
    'kg',
    'DEFRA',
    `${DEFRA} Waste disposal — construction closed-loop / open-loop recycling, 1.01398 kg CO₂e/tonne.`,
    GOV_URL,
  ),
  factor(
    'water_m3',
    'Mains water supply',
    'Water',
    'Scope 3',
    0.1913,
    'm³',
    'DEFRA',
    `${DEFRA} Water supply.`,
    GOV_URL,
  ),
  factor(
    'crew_van_km',
    'Average car (unknown fuel)',
    'Crew transport',
    'Scope 3',
    0.16591,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average car, unknown fuel.`,
    GOV_URL,
  ),
  factor(
    'crew_bus_pkm',
    'Average local bus',
    'Crew transport',
    'Scope 3',
    0.10151,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — average local bus.`,
    GOV_URL,
  ),
  factor(
    'crew_rail_pkm',
    'National rail',
    'Crew transport',
    'Scope 3',
    0.03092,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — national rail.`,
    GOV_URL,
  ),
  factor(
    'material_concrete_t',
    'Concrete (primary production)',
    'Bulk materials',
    'Scope 3',
    118.80307,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction concrete, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_steel_t',
    'Structural steel sections (A1–A3)',
    'Bulk materials',
    'Scope 3',
    1550,
    't',
    'ICE',
    `${ICE} Industry-average / section steel ≈ 1.55 kg CO₂e/kg. Headline steel factors were unchanged from v3.0 to v4.1.`,
    ICE_URL,
  ),
  factor(
    'material_timber_t',
    'Wood (primary production)',
    'Bulk materials',
    'Scope 3',
    269.50416,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction wood, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_asphalt_t',
    'Asphalt (primary production)',
    'Bulk materials',
    'Scope 3',
    39.21249,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction asphalt, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_aggregates_t',
    'Aggregates (primary production)',
    'Bulk materials',
    'Scope 3',
    7.80307,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction aggregates, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_cement_t',
    'Cement CEM I / Portland (A1–A3)',
    'Bulk materials',
    'Scope 3',
    910,
    't',
    'ICE',
    `${ICE} CEM I (Portland) ≈ 0.91 kg CO₂e/kg.`,
    ICE_URL,
  ),
  factor(
    'material_rebar_t',
    'Reinforcing steel (A1–A3)',
    'Bulk materials',
    'Scope 3',
    1990,
    't',
    'ICE',
    `${ICE} Reinforcing steel ≈ 1.99 kg CO₂e/kg. No newer published replacement for this headline row.`,
    ICE_URL,
  ),
  factor(
    'material_metals_t',
    'Construction metals (primary production)',
    'Bulk materials',
    'Scope 3',
    3821.94858,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction metals, primary material production (mixed metals, not section steel).`,
    GOV_URL,
  ),

  // ── Well-to-tank (WTT) factors ──────────────────────────────────────────
  factor(
    'wtt_diesel_litre',
    'WTT — diesel',
    'WTT fuels',
    'Scope 3',
    0.61101,
    'L',
    'DEFRA',
    `${DEFRA} WTT-fuels — diesel (average biofuel blend), litres.`,
    GOV_URL,
  ),
  factor(
    'wtt_petrol_litre',
    'WTT — petrol',
    'WTT fuels',
    'Scope 3',
    0.58094,
    'L',
    'DEFRA',
    `${DEFRA} WTT-fuels — petrol (average biofuel blend), litres.`,
    GOV_URL,
  ),
  factor(
    'wtt_lpg_litre',
    'WTT — LPG',
    'WTT fuels',
    'Scope 3',
    0.18551,
    'L',
    'DEFRA',
    `${DEFRA} WTT-fuels — LPG, litres.`,
    GOV_URL,
  ),
  factor(
    'wtt_gas_oil_litre',
    'WTT — gas oil',
    'WTT fuels',
    'Scope 3',
    0.62665,
    'L',
    'DEFRA',
    `${DEFRA} WTT-fuels — gas oil, litres.`,
    GOV_URL,
  ),
  factor(
    'wtt_natural_gas_kwh',
    'WTT — natural gas',
    'WTT fuels',
    'Scope 3',
    0.03021,
    'kWh',
    'DEFRA',
    `${DEFRA} WTT-fuels — natural gas, kWh (Gross CV), to match the combustion Gross CV factor.`,
    GOV_URL,
  ),
  factor(
    'wtt_electricity_kwh',
    'WTT — UK grid electricity (generation)',
    'WTT energy',
    'Scope 3',
    0.03682,
    'kWh',
    'DESNZ',
    `${DESNZ} WTT- UK electricity (generation). Transmission and distribution stays on electricity_td_kwh.`,
    GOV_URL,
  ),

  // ── Business travel: flights ────────────────────────────────────────────
  factor(
    'flight_domestic_pkm',
    'Domestic flights',
    'Business travel',
    'Scope 3',
    0.22928,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–air — domestic, average passenger, with RF.`,
    GOV_URL,
  ),
  factor(
    'flight_shorthaul_pkm',
    'Short-haul flights (economy)',
    'Business travel',
    'Scope 3',
    0.12576,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–air — short-haul, economy class, with RF.`,
    GOV_URL,
  ),
  factor(
    'flight_longhaul_economy_pkm',
    'Long-haul flights (economy)',
    'Business travel',
    'Scope 3',
    0.11704,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–air — long-haul, economy class, with RF.`,
    GOV_URL,
  ),
  factor(
    'flight_longhaul_business_pkm',
    'Long-haul flights (business)',
    'Business travel',
    'Scope 3',
    0.3394,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–air — long-haul, business class, with RF.`,
    GOV_URL,
  ),

  // ── Business travel: hotel nights ───────────────────────────────────────
  factor(
    'hotel_uk_night',
    'Hotel stay (UK)',
    'Business travel',
    'Scope 3',
    10.4,
    'night',
    'DEFRA',
    `${DEFRA} Hotel stay — UK, per room per night.`,
    GOV_URL,
  ),
  factor(
    'hotel_overseas_night',
    'Hotel stay (overseas)',
    'Business travel',
    'Scope 3',
    40.28648648648648,
    'night',
    'DEFRA',
    `${DEFRA} 2026 has no single “overseas” hotel row. Unweighted mean of the 37 published non-UK, non-“UK (London)” country factors.`,
    GOV_URL,
  ),

  // ── Business travel: land / taxis ───────────────────────────────────────
  factor(
    'taxi_km',
    'Regular taxi',
    'Business travel',
    'Scope 3',
    0.20806,
    'km',
    'DEFRA',
    `${DEFRA} Business travel–land — regular taxi, kg CO₂e per vehicle-km (not passenger.km).`,
    GOV_URL,
  ),

  // ── Employee commuting ──────────────────────────────────────────────────
  factor(
    'commute_car_km',
    'Average car (commuting)',
    'Employee commuting',
    'Scope 3',
    0.16591,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average car, unknown fuel.`,
    GOV_URL,
  ),
  factor(
    'commute_bus_pkm',
    'Average local bus (commuting)',
    'Employee commuting',
    'Scope 3',
    0.10151,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — average local bus.`,
    GOV_URL,
  ),
  factor(
    'commute_rail_pkm',
    'National rail (commuting)',
    'Employee commuting',
    'Scope 3',
    0.03092,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — national rail.`,
    GOV_URL,
  ),
  factor(
    'commute_motorbike_km',
    'Average motorbike (commuting)',
    'Employee commuting',
    'Scope 3',
    0.11367,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average motorbike.`,
    GOV_URL,
  ),

  // ── Wastewater ──────────────────────────────────────────────────────────
  factor(
    'wastewater_m3',
    'Wastewater treatment',
    'Wastewater',
    'Scope 3',
    0.17088,
    'm³',
    'DEFRA',
    `${DEFRA} Water treatment.`,
    GOV_URL,
  ),

  // ── Purchased goods — spend-based (EEIO) ────────────────────────────────
  factor(
    'purchased_goods_gbp',
    'Purchased goods & services (UK average)',
    'Purchased goods',
    'Scope 3',
    855.9280439858236,
    '£k',
    'EIO',
    `${EIO} Unweighted mean of the 18 non-zero SIC-19 GHG multipliers (Construction is published as ~0 and is excluded).`,
    SPEND_URL,
  ),
  factor(
    'capital_goods_gbp',
    'Capital goods (UK average)',
    'Capital goods',
    'Scope 3',
    698.7898127964011,
    '£k',
    'EIO',
    `${EIO} SIC C Manufacturing.`,
    SPEND_URL,
  ),

  // ── Additional construction materials ───────────────────────────────────
  factor(
    'material_glass_t',
    'Glass (primary production)',
    'Bulk materials',
    'Scope 3',
    1402.76667,
    't',
    'DEFRA',
    `${DEFRA} Material use — other / glass, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_aluminium_t',
    'Aluminium (primary production)',
    'Bulk materials',
    'Scope 3',
    13100,
    't',
    'ICE',
    `${ICE} Primary / virgin aluminium ≈ 13.1 kg CO₂e/kg (not the industry-average recycled blend).`,
    ICE_URL,
  ),
  factor(
    'material_bricks_t',
    'Bricks (generic)',
    'Bulk materials',
    'Scope 3',
    241.80307,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction bricks, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_insulation_t',
    'Insulation (general)',
    'Bulk materials',
    'Scope 3',
    1861.80307,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction insulation, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_plasterboard_t',
    'Plasterboard',
    'Bulk materials',
    'Scope 3',
    120.05,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction plasterboard, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_copper_t',
    'Copper (primary)',
    'Bulk materials',
    'Scope 3',
    3830,
    't',
    'ICE',
    `${ICE} Copper ≈ 3.83 kg CO₂e/kg.`,
    ICE_URL,
  ),
  factor(
    'material_pvc_t',
    'PVC pipe / general',
    'Bulk materials',
    'Scope 3',
    2942.43735,
    't',
    'DEFRA',
    `${DEFRA} Material use — plastics: PVC (incl. forming), primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_soil_t',
    'Soil / earthworks',
    'Bulk materials',
    'Scope 3',
    0,
    't',
    'DEFRA',
    `${DEFRA} Material use — soils primary production is no longer published in 2026 (cell withdrawn). Conversion is 0 rather than an invented replacement. Prefer a site-specific or EPD factor.`,
    GOV_URL,
  ),
  factor(
    'material_lime_t',
    'Lime (general)',
    'Bulk materials',
    'Scope 3',
    760,
    't',
    'ICE',
    `${ICE} Last published ICE general lime ≈ 0.76 kg CO₂e/kg. No DESNZ 2026 or v4.1 headline replacement found.`,
    ICE_URL,
  ),

  // ── Mining: explosives (Scope 1 combustion) and fugitive methane ────────
  factor(
    'explosives_anfo_kg',
    'ANFO explosives (combustion)',
    'Explosives',
    'Scope 1',
    0.22,
    'kg',
    'EPA',
    `${NPI} ANFO ≈ 0.22 kg CO₂e/kg explosive (≈6% fuel oil, complete oxidation of fuel carbon). Covers blast CO₂, not manufactured embodied carbon.`,
    NPI_URL,
  ),
  factor(
    'explosives_emulsion_kg',
    'Emulsion explosives (combustion)',
    'Explosives',
    'Scope 1',
    0.14,
    'kg',
    'EPA',
    `${NPI} Emulsion blasting agent ≈ 0.14 kg CO₂e/kg explosive, reflecting lower hydrocarbon fuel content.`,
    NPI_URL,
  ),
  factor(
    'mine_ch4_t',
    'Mine methane (tonnes CH₄)',
    'Mine gas',
    'Scope 1',
    28000,
    't',
    'IPCC',
    `${IPCC} 1 t CH₄ × GWP 28 = 28,000 kg CO₂e.`,
    IPCC_URL,
  ),
  factor(
    'mine_ch4_kg',
    'Mine methane (kg CH₄)',
    'Mine gas',
    'Scope 1',
    28,
    'kg',
    'IPCC',
    `${IPCC} 1 kg CH₄ × GWP 28 = 28 kg CO₂e.`,
    IPCC_URL,
  ),
  factor(
    'mine_ch4_m3',
    'Mine methane (m³ CH₄)',
    'Mine gas',
    'Scope 1',
    20.08,
    'm³',
    'IPCC',
    `${IPCC} CH₄ density 0.717 kg/m³ at 0 °C, 1 atm × GWP 28 ≈ 20.08 kg CO₂e/m³. Convert ventilation air to CH₄ first.`,
    IPCC_URL,
  ),
]

export const PLACEHOLDER_FACTORS = FACTOR_CATALOG
