import type { EmissionFactor, Scope, SourceFamily } from './types'

const YEAR = '2025'
const VERIFIED = '2026-09-03'
const GOV_URL =
  'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2025'
const ICE_URL = 'https://circularecology.com/embodied-carbon-footprint-database.html'

const DEFRA =
  'UK GHG Conversion Factors for Company Reporting 2025 (DESNZ / DEFRA; formerly BEIS). kg CO₂e, IPCC AR5. Published 10 June 2025.'
const DESNZ =
  'UK GHG Conversion Factors for Company Reporting 2025 — electricity / heat (DESNZ). kg CO₂e, IPCC AR5. Published 10 June 2025.'
const ICE =
  'Inventory of Carbon and Energy (ICE) Database v3.0, Circular Ecology / University of Bath. Cradle-to-gate A1–A3, kg CO₂e per kg converted to per tonne.'

function factor(
  key: string,
  name: string,
  category: string,
  scope: Scope,
  conversionValue: number,
  unit: string,
  sourceFamily: SourceFamily,
  source: string,
  sourceUrl: string,
): EmissionFactor {
  return {
    key,
    name,
    category,
    scope,
    conversionValue,
    unit,
    sourceFamily,
    source,
    sourceUrl,
    region: 'United Kingdom',
    validFrom: `${YEAR}-01-01`,
    lastVerifiedAt: VERIFIED,
    isPlaceholder: false,
  }
}

export const FACTOR_CATALOG: EmissionFactor[] = [
  factor(
    'electricity_grid_kwh',
    'UK grid electricity (generated)',
    'Site energy',
    'Scope 2',
    0.177,
    'kWh',
    'DESNZ',
    `${DESNZ} Electricity generated, location-based.`,
    GOV_URL,
  ),
  factor(
    'electricity_renewable_kwh',
    'On-site renewable electricity',
    'Site energy',
    'Scope 2',
    0,
    'kWh',
    'DESNZ',
    `${DESNZ} Location-based residual for on-site generation (no grid factor).`,
    GOV_URL,
  ),
  factor(
    'electricity_td_kwh',
    'UK electricity T&D losses',
    'Site energy',
    'Scope 3',
    0.01853,
    'kWh',
    'DESNZ',
    `${DESNZ} Transmission and distribution losses.`,
    GOV_URL,
  ),
  factor(
    'heat_steam_kwh',
    'District / onsite heat and steam',
    'Site energy',
    'Scope 2',
    0.17529,
    'kWh',
    'DESNZ',
    `${DESNZ} Heat and steam.`,
    GOV_URL,
  ),
  factor(
    'natural_gas_kwh',
    'Natural gas (gross CV)',
    'Site fuel',
    'Scope 1',
    0.18296,
    'kWh',
    'DEFRA',
    `${DEFRA} Fuels — natural gas, gross CV.`,
    GOV_URL,
  ),
  factor(
    'natural_gas_m3',
    'Natural gas',
    'Site fuel',
    'Scope 1',
    2.0667,
    'm³',
    'DEFRA',
    `${DEFRA} Fuels — natural gas, cubic metres.`,
    GOV_URL,
  ),
  factor(
    'diesel_litre',
    'Diesel (average biofuel blend)',
    'Site fuel',
    'Scope 1',
    2.5708,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — diesel (average biofuel blend).`,
    GOV_URL,
  ),
  factor(
    'petrol_litre',
    'Petrol (average biofuel blend)',
    'Site fuel',
    'Scope 1',
    2.0692,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — petrol (average biofuel blend).`,
    GOV_URL,
  ),
  factor(
    'lpg_litre',
    'LPG',
    'Site fuel',
    'Scope 1',
    1.5571,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — LPG.`,
    GOV_URL,
  ),
  factor(
    'hvo_litre',
    'HVO / renewable diesel',
    'Site fuel',
    'Scope 1',
    0.03558,
    'L',
    'DEFRA',
    `${DEFRA} Bioenergy — HVO biodiesel, Scope 1 CH₄/N₂O only.`,
    GOV_URL,
  ),
  factor(
    'gas_oil_litre',
    'Red diesel / gas oil (plant)',
    'Heavy machinery',
    'Scope 1',
    2.7554,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — gas oil.`,
    GOV_URL,
  ),
  factor(
    'marine_gas_oil_litre',
    'Marine gas oil',
    'Sea freight',
    'Scope 1',
    2.7714,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — marine gas oil.`,
    GOV_URL,
  ),
  factor(
    'aviation_turbine_litre',
    'Aviation turbine fuel',
    'Air freight',
    'Scope 1',
    2.5427,
    'L',
    'DEFRA',
    `${DEFRA} Fuels — aviation turbine fuel.`,
    GOV_URL,
  ),
  factor(
    'r404a_kg',
    'R-404A refrigerant',
    'Refrigerants',
    'Scope 1',
    3943,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of R-404A (IPCC AR5).`,
    GOV_URL,
  ),
  factor(
    'r410a_kg',
    'R-410A refrigerant',
    'Refrigerants',
    'Scope 1',
    1924,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of R-410A (IPCC AR5).`,
    GOV_URL,
  ),
  factor(
    'r134a_kg',
    'HFC-134a refrigerant',
    'Refrigerants',
    'Scope 1',
    1300,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of HFC-134a (IPCC AR5).`,
    GOV_URL,
  ),
  factor(
    'co2_kg',
    'Carbon dioxide refrigerant',
    'Refrigerants',
    'Scope 1',
    1,
    'kg',
    'DEFRA',
    `${DEFRA} Refrigerants — GWP of CO₂.`,
    GOV_URL,
  ),
  factor(
    'freight_road_tkm',
    'Road freight (all HGVs, average laden)',
    'Road freight',
    'Scope 3',
    0.10163,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — all HGVs, average laden.`,
    GOV_URL,
  ),
  factor(
    'freight_rail_tkm',
    'Rail freight',
    'Rail freight',
    'Scope 3',
    0.02779,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — freight train.`,
    GOV_URL,
  ),
  factor(
    'freight_sea_tkm',
    'Sea freight (container ship, average)',
    'Sea freight',
    'Scope 3',
    0.01612,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — cargo ship, container, average.`,
    GOV_URL,
  ),
  factor(
    'freight_air_tkm',
    'Air freight (short-haul, without RF)',
    'Air freight',
    'Scope 3',
    0.75539,
    'tkm',
    'DEFRA',
    `${DEFRA} Freighting goods — freight flights, short-haul, without radiative forcing.`,
    GOV_URL,
  ),
  factor(
    'waste_landfill_kg',
    'Construction waste to landfill',
    'Waste',
    'Scope 3',
    0.0012634,
    'kg',
    'DEFRA',
    `${DEFRA} Waste disposal — construction (concrete/aggregates/asphalt) landfill, 1.2634 kg CO₂e/tonne.`,
    GOV_URL,
  ),
  factor(
    'waste_recycling_kg',
    'Construction waste recycled',
    'Waste',
    'Scope 3',
    0.0010084,
    'kg',
    'DEFRA',
    `${DEFRA} Waste disposal — construction closed-loop / open-loop recycling, 1.0084 kg CO₂e/tonne.`,
    GOV_URL,
  ),
  factor(
    'water_m3',
    'Mains water supply',
    'Water',
    'Scope 3',
    0.1913,
    'm³',
    'DEFRA',
    `${DEFRA} Water supply.`,
    GOV_URL,
  ),
  factor(
    'crew_van_km',
    'Average car (unknown fuel)',
    'Crew transport',
    'Scope 3',
    0.16725,
    'km',
    'DEFRA',
    `${DEFRA} Passenger vehicles — average car, unknown fuel.`,
    GOV_URL,
  ),
  factor(
    'crew_bus_pkm',
    'Average local bus',
    'Crew transport',
    'Scope 3',
    0.10385,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — average local bus. Official methodology Table 26: 103.85 g CO₂e/pkm.`,
    GOV_URL,
  ),
  factor(
    'crew_rail_pkm',
    'National rail',
    'Crew transport',
    'Scope 3',
    0.03546,
    'pkm',
    'DEFRA',
    `${DEFRA} Business travel–land — national rail.`,
    GOV_URL,
  ),
  factor(
    'material_concrete_t',
    'Concrete (primary production)',
    'Bulk materials',
    'Scope 3',
    118.7931,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction concrete, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_steel_t',
    'Structural steel sections (A1–A3)',
    'Bulk materials',
    'Scope 3',
    1550,
    't',
    'ICE',
    `${ICE} Steel, section: 1.55 kg CO₂e/kg.`,
    ICE_URL,
  ),
  factor(
    'material_timber_t',
    'Wood (primary production)',
    'Bulk materials',
    'Scope 3',
    269.5042,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction wood, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_asphalt_t',
    'Asphalt (primary production)',
    'Bulk materials',
    'Scope 3',
    39.2125,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction asphalt, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_aggregates_t',
    'Aggregates (primary production)',
    'Bulk materials',
    'Scope 3',
    7.7931,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction aggregates, primary material production.`,
    GOV_URL,
  ),
  factor(
    'material_cement_t',
    'Cement CEM I / Portland (A1–A3)',
    'Bulk materials',
    'Scope 3',
    912,
    't',
    'ICE',
    `${ICE} Cement CEM I (Portland): 0.912 kg CO₂e/kg from the ICE cement–mortar–concrete model.`,
    ICE_URL,
  ),
  factor(
    'material_rebar_t',
    'Reinforcing steel (A1–A3)',
    'Bulk materials',
    'Scope 3',
    1990,
    't',
    'ICE',
    `${ICE} Steel, rebar: 1.99 kg CO₂e/kg.`,
    ICE_URL,
  ),
  factor(
    'material_metals_t',
    'Construction metals (primary production)',
    'Bulk materials',
    'Scope 3',
    3824.0934,
    't',
    'DEFRA',
    `${DEFRA} Material use — construction metals, primary material production (mixed metals, not section steel).`,
    GOV_URL,
  ),
]

export const PLACEHOLDER_FACTORS = FACTOR_CATALOG
