import {
  BarChart3,
  Bike,
  Briefcase,
  Building2,
  Bus,
  Droplets,
  FileText,
  Flame,
  Fuel,
  Grid3x3,
  Hammer,
  HardHat,
  HelpCircle,
  LayoutDashboard,
  Mountain,
  Package,
  Pickaxe,
  Plane,
  Plus,
  Ship,
  ShoppingCart,
  SlidersHorizontal,
  Snowflake,
  Target,
  Trash2,
  Truck,
  Users,
  Warehouse,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  site_electricity: Zap,
  site_fuel: Fuel,
  heavy_machinery: Hammer,
  explosives: Pickaxe,
  fleet: Truck,
  refrigerants: Snowflake,
  mine_gas: Mountain,
  road_freight: Warehouse,
  rail_freight: Grid3x3,
  sea_freight: Ship,
  air_freight: Plane,
  waste: Trash2,
  water: Droplets,
  crew_transport: Bus,
  bulk_materials: Package,
  heat_steam: Flame,
  subcontractor: HardHat,
  business_travel: Briefcase,
  employee_commuting: Bike,
  wastewater: Droplets,
  purchased_goods: ShoppingCart,
  energy_wtt: Fuel,
  custom: Plus,
  input: FileText,
  dashboard: LayoutDashboard,
  analysis: BarChart3,
  combined: Grid3x3,
  faqs: HelpCircle,
  targets: Target,
  users: Users,
  sites: Building2,
  factors: SlidersHorizontal,
  learn: HelpCircle,
}
